RAG FROM SCRATCH

we are going to build NitriChat to "Chat with a nutrition textbook."<br>
Specially;<br> <br>
1.Open a pdf document<br>
2.Format the text of the PDF textbook ready for the embedding model.<br>
3.Embeded all of the chunks of text in the textbook and turn them into numerical representation(embedding)which can store for later.<br>
4.Build a retrieval system that uses vector search to find a relevant chunk of text based on a query.<br>
5.Create a prompt that incorporates the retrieved pieces of text.<br>
6.Generate an answer to a query based on the passage of the notebook with LLM.

<br> Summary!<br>
1.Steps 1-3: Document preprocessing and embedding creation.<br>
2.Steps 4-6: Search and answer.<br>
3.Embed text chunks with embedding model.<br>
4.Save embeddings to file for later(embeddings will store on file for many years or until you lose your hard drive.)

# Import PDF Document

In [1]:
# import requests
# import os

# pdf_path = "human-nutrition-pdf"

# #Download pdf and save
# if not os.path.exists(pdf_path):
#   print("Downlaoding file....")
#   url = ""
#   file_name = pdf_path
#   response = requests.get(url)
#   #check download succeed
#   if response.status_code == 200:
#     with open(file_name, 'wb')as f:
#       f.write(response.content)
#       print(f"download complete and saved to {file_name}")
#   else:
#     print(f"Download failed. status code:{response.status_code} ")

# else:
#     print(f"file already exits {pdf_path}")

In [2]:
!pip install pymupdf

Collecting pymupdf
  Downloading pymupdf-1.27.2.2-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Downloading pymupdf-1.27.2.2-cp310-abi3-manylinux_2_28_x86_64.whl (24.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.9/24.9 MB 68.9 MB/s eta 0:00:00
Installing collected packages: pymupdf
Successfully installed pymupdf-1.27.2.2

In [3]:
import pymupdf
import re

pdf_path = "/content/human-nutrition.pdf"
def text_formatted(text: str) -> str:
  return re.sub(r'\s+', ' ', text).strip()  # \n मात्र नभई सबै extra spaces पनि हटाउँछ
  return cleaned_text

def extract_text_from_pdf(pdf_path) -> list[dict]:
    doc = pymupdf.open(pdf_path)

    pages_and_text = []
    for page_number,page in enumerate(doc):
      text = page.get_text()
      text = text_formatted(text)
      pages_and_text.append({"page_number":page_number-19,
                             "page_character_count":len(text),
                             "page_word_count":len(text.split()),
                             "page_sentence_count":len(text.split(".")),
                             "text":text})
    return pages_and_text

pages_and_text = extract_text_from_pdf(pdf_path=pdf_path)
pages_and_text[20]

{'page_number': 1,
 'page_character_count': 66,
 'page_word_count': 12,
 'page_sentence_count': 1,
 'text': 'PART I BASIC CONCEPTS IN NUTRITION BASIC CONCEPTS IN NUTRITION | 1'}

In [4]:
import random
random.sample(pages_and_text,k=2)

[{'page_number': 512,
  'page_character_count': 3085,
  'page_word_count': 447,
  'page_sentence_count': 30,
  'text': 'pregnant women in the world have iron-deficiency anemia. 3 The main causes of iron deficiency worldwide are parasitic worm infections in the gut, causing excessive blood loss, and malaria, a parasitic disease that destroys red blood cells. In the developed world, iron deficiency is more the result of dietary insufficiency and/or excessive blood loss during menstruation or childbirth. At-Risk Populations Infants, children, adolescents, and women are the populations most at risk worldwide for iron-deficiency anemia by all causes. Infants, children, and even teens require more iron because iron is essential for growth. In these populations, iron deficiency (and eventually iron-deficiency anemia) can also cause the following signs and symptoms: poor growth, failure to thrive, and poor performance in school, as well as mental, motor, and behavioral disorders. Women who experience heavy menstrual bleeding or who are pregnant require more iron in their diet. One more high-risk group is the elderly. Both elderly men and women have a high incidence of anemia, and the most common causes are dietary iron deficiency and chronic diseases such as ulcers, inflammatory diseases, and cancer. Additionally, those who have recently suffered from traumatic blood loss, frequently donate blood, or take excessive antacids for heartburn need more iron in the diet. Preventing Iron-Deficiency Anemia In young children, iron-deficiency anemia can cause significant motor, mental, and behavioral abnormalities that are long-lasting. In the United States, the high incidence of iron-deficiency anemia in infants and children was a major public health problem prior to the early 1970s. Still, now the incidence has been greatly reduced. This achievement was accomplished by implementing the screening of infants for iron-deficiency anemia in the health sector as a common practice, advocating the fortification of infant formulas and cereals with iron, and distributing them in supplemental food programs, such as those within Women, Infants, and Children (WIC). Breastfeeding, iron supplementation, and delaying the introduction of cow’s milk for at least the first twelve months of life were also encouraged. These practices were implemented across the socioeconomic spectrum, and by the 1980s, iron-deficiency anemia in infants had significantly declined. Other solutions had to be introduced in young children, who no longer were fed breast milk or fortified formulas and were consuming cow’s milk. The following solutions were introduced to parents: provide a diet rich in sources of iron and vitamin C, limit cow’s milk consumption to less than twenty-four ounces per day, and take a multivitamin containing iron. In the third world, iron-deficiency anemia remains a significant public health challenge. The World Bank 3. Walters, D., et al. (2017). “An Investment Framework for Meeting the Global Nutrition Target for Anemia”. The World Bank. https://openknowledge.worldbank.org/server/api/core/bitstreams/91e969b7-f635-57b2-8fd0-8702d9b2357c/content. Accessed July 28, 2025. 512 | IRON'},
 {'page_number': 45,
  'page_character_count': 42,
  'page_word_count': 10,
  'page_sentence_count': 1,
  'text': 'PART II THE HUMAN BODY THE HUMAN BODY | 45'}]

In [5]:
#convert to dataframe
import pandas as pd

df = pd.DataFrame(pages_and_text)
df.head(5)

,page_number,page_character_count,page_word_count,page_sentence_count,text
0,-19,15,2,1,Human Nutrition
1,-18,0,0,1,
2,-17,105,14,1,HUMAN NUTRITION Louisiana Edition MELISSA JOHN...
3,-16,238,30,3,Human Nutrition Copyright © 2022 by Melissa Jo...
4,-15,518,79,3,CONTENTS Preface xiii About the Contributors x...

Further Preprocessing the Text => Spliting Pages to Sentences.

Two ways:<br>
1.By using split"."<br>
2.By using NLP library such as Spacy and NLTP.We gonna use spacy for now.

In [6]:
!pip install spacy

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.24.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.5.1)
Requirement already satisfied: httpx>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.1.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)

In [7]:
import spacy

nlp = spacy.blank("en")
nlp.add_pipe("sentencizer")

#Demo
text = "This is sen one.This is sen two."
doc = nlp(text)

list(doc.sents)

[This is sen one., This is sen two.]

In [8]:
# sentence = []
# for pages in pages_and_text:
#   doc = nlp(pages["text"])
#   sentence.extend(sent.text.strip() for sent in doc.sents)

# sentence[1]

In [9]:
#optional approach be like and good approach
for items in pages_and_text:

  docs = nlp(items["text"])
  items["sentence"] = [str(sentence).strip() for sentence in docs.sents]

  items["sentence_count"] = len(items["sentence"])

pages_and_text[25]

{'page_number': 6,
 'page_character_count': 1846,
 'page_word_count': 281,
 'page_sentence_count': 15,
 'text': 'Lipids Lipids are also a family of molecules composed of carbon, hydrogen, and oxygen, but unlike carbohydrates, they are insoluble in water. Lipids are found predominantly in butter, oils, meats, dairy products, nuts, and seeds, and in many processed foods. The three main types of lipids are triglycerides (triacylglycerols), phospholipids, and sterols. The main job of lipids is to provide or store energy. Lipids provide more energy per gram than carbohydrates (nine kilocalories per gram of lipids versus four kilocalories per gram of carbohydrates). In addition to energy storage, lipids serve as a major component of cell membranes, surround and protect organs (in fat-storing tissues), provide insulation to aid in temperature regulation, and regulate many other functions in the body. Proteins Proteins are macromolecules composed of chains of subunits called amino acids. Amino acids are simple subunits composed of carbon, oxygen, hydrogen, and nitrogen. Food sources of proteins include meats, dairy products, seafood, and a variety of different plant-based foods, most notably soy. The word protein comes from a Greek word meaning “of primary importance,” which is an apt description of these macronutrients; they are also known colloquially as the “workhorses” of life. Proteins provide four kilocalories of energy per gram; however, providing energy is not protein’s most important function. Proteins provide structure to bones, muscles, and skin, and play a role in conducting most of the chemical reactions that take place in the body. Scientists estimate that more than one hundred thousand different proteins exist within the human body. The genetic codes in DNA are basically protein recipes that determine the order in which 20 different amino acids are bound together to make thousands of specific proteins. 6 | INTRODUCTION',
 'sentence': ['Lipids Lipids are also a family of molecules composed of carbon, hydrogen, and oxygen, but unlike carbohydrates, they are insoluble in water.',
  'Lipids are found predominantly in butter, oils, meats, dairy products, nuts, and seeds, and in many processed foods.',
  'The three main types of lipids are triglycerides (triacylglycerols), phospholipids, and sterols.',
  'The main job of lipids is to provide or store energy.',
  'Lipids provide more energy per gram than carbohydrates (nine kilocalories per gram of lipids versus four kilocalories per gram of carbohydrates).',
  'In addition to energy storage, lipids serve as a major component of cell membranes, surround and protect organs (in fat-storing tissues), provide insulation to aid in temperature regulation, and regulate many other functions in the body.',
  'Proteins Proteins are macromolecules composed of chains of subunits called amino acids.',
  'Amino acids are simple subunits composed of carbon, oxygen, hydrogen, and nitrogen.',
  'Food sources of proteins include meats, dairy products, seafood, and a variety of different plant-based foods, most notably soy.',
  'The word protein comes from a Greek word meaning “of primary importance,” which is an apt description of these macronutrients; they are also known colloquially as the “workhorses” of life.',
  'Proteins provide four kilocalories of energy per gram; however, providing energy is not protein’s most important function.',
  'Proteins provide structure to bones, muscles, and skin, and play a role in conducting most of the chemical reactions that take place in the body.',
  'Scientists estimate that more than one hundred thousand different proteins exist within the human body.',
  'The genetic codes in DNA are basically protein recipes that determine the order in which 20 different amino acids are bound together to make thousands of specific proteins.',
  '6 | INTRODUCTION'],
 'sentence_count': 15}

In [10]:
df = pd.DataFrame(pages_and_text)
df.describe().round(1)

,page_number,page_character_count,page_word_count,page_sentence_count,sentence_count
count,906.0,906.0,906.0,906.0,906.0
mean,433.5,1488.1,226.3,19.1,14.3
std,261.7,935.4,143.1,15.4,10.6
min,-19.0,0.0,0.0,1.0,0.0
25%,207.2,725.5,111.2,8.0,5.0
50%,433.5,1418.0,218.0,16.0,12.0
75%,659.8,2207.5,331.8,28.0,21.0
max,886.0,3670.0,598.0,110.0,59.0

Now,lets further chunks the sentences into the smaller chunks.i.e into 10 sentences.

Why chunking?<br>
1.Our text are easier to filter.<br>
2.Our chunk can be fit into our embedding model.<br>
3.Our context passed to LLM can be more specific and focused.

We can chunk sentence using Langchain but now we will gonna use python.

In [11]:
pages_and_text[24]

{'page_number': 5,
 'page_character_count': 2975,
 'page_word_count': 459,
 'page_sentence_count': 28,
 'text': 'Macronutrients Nutrients that are needed in large amounts are called macronutrients. There are three classes of macronutrients: carbohydrates, lipids, and proteins. Through various biological processes occurring in the body, these nutrients can be metabolized to produce cellular energy. The energy from macronutrients comes from their chemical bonds. This chemical energy is converted into cellular energy that is then utilized to perform work, allowing our bodies to conduct their basic functions. The energy obtained from food, which thus becomes cellular energy, is measured in calorie units. A unit of measurement of food energy is the calorie. On nutrition food labels, the amount given for “calories” is actually equivalent to each calorie multiplied by one thousand. A kilocalorie (one thousand calories, denoted with a small “c”) is synonymous with the “Calorie” (with a capital “C”) on nutrition food labels. Although water does not yield calories, it is considered to be a macronutrient because it is needed in large amounts daily. Water is also a macronutrient in the sense that you require a large amount of it, but unlike the other macronutrients, it does not yield calories. Carbohydrates Carbohydrates are molecules composed of the elements carbon, hydrogen, and oxygen. The major food sources of carbohydrates are grains, milk, fruits, and starchy vegetables, like potatoes and rice. Non-starchy vegetables also contain carbohydrates, but in lesser quantities. Carbohydrates are broadly classified into two forms based on their chemical structure: simple carbohydrates, often called simple sugars; and complex carbohydrates. Simple carbohydrates consist of one or two basic units. Examples of simple sugars include sucrose, the type of sugar you would have in a bowl on the breakfast table, and glucose, the type of sugar that circulates in your blood. Complex carbohydrates are long chains of simple sugars that can be unbranched or branched. During digestion, the body breaks down digestible complex carbohydrates to simple sugars, mostly glucose. Glucose is then transported to all our cells, where it is stored, used to make energy, or used to build macromolecules. Fiber is also a complex carbohydrate, but it cannot be broken down by digestive enzymes in the human intestine. As a result, it passes through the digestive tract undigested unless the bacteria that inhabit the colon or large intestine break it down. One gram of digestible carbohydrates yields four kilocalories of energy for the cells in the body to perform work. In addition to providing energy and serving as building blocks for bigger macromolecules, carbohydrates are essential for the proper functioning of the nervous system, heart, and kidneys. As mentioned, glucose can be stored in the body for future use. In humans, the storage molecule of carbohydrates is called glycogen, and in plants, it is known as starch. Glycogen and starch are complex carbohydrates. INTRODUCTION | 5',
 'sentence': ['Macronutrients Nutrients that are needed in large amounts are called macronutrients.',
  'There are three classes of macronutrients: carbohydrates, lipids, and proteins.',
  'Through various biological processes occurring in the body, these nutrients can be metabolized to produce cellular energy.',
  'The energy from macronutrients comes from their chemical bonds.',
  'This chemical energy is converted into cellular energy that is then utilized to perform work, allowing our bodies to conduct their basic functions.',
  'The energy obtained from food, which thus becomes cellular energy, is measured in calorie units.',
  'A unit of measurement of food energy is the calorie.',
  'On nutrition food labels, the amount given for “calories” is actually equivalent to each calorie multiplied by one thousand.',
  'A kilocalorie (one thousand calories, denoted with a small “c”) is synonymous with the “Calorie” (with a capital “C”) on nutrition food labels.',
  'Although water does not yield calories, it is considered to be a macronutrient because it is needed in large amounts daily.',
  'Water is also a macronutrient in the sense that you require a large amount of it, but unlike the other macronutrients, it does not yield calories.',
  'Carbohydrates Carbohydrates are molecules composed of the elements carbon, hydrogen, and oxygen.',
  'The major food sources of carbohydrates are grains, milk, fruits, and starchy vegetables, like potatoes and rice.',
  'Non-starchy vegetables also contain carbohydrates, but in lesser quantities.',
  'Carbohydrates are broadly classified into two forms based on their chemical structure: simple carbohydrates, often called simple sugars; and complex carbohydrates.',
  'Simple carbohydrates consist of one or two basic units.',
  'Examples of simple sugars include sucrose, the type of sugar you would have in a bowl on the breakfast table, and glucose, the type of sugar that circulates in your blood.',
  'Complex carbohydrates are long chains of simple sugars that can be unbranched or branched.',
  'During digestion, the body breaks down digestible complex carbohydrates to simple sugars, mostly glucose.',
  'Glucose is then transported to all our cells, where it is stored, used to make energy, or used to build macromolecules.',
  'Fiber is also a complex carbohydrate, but it cannot be broken down by digestive enzymes in the human intestine.',
  'As a result, it passes through the digestive tract undigested unless the bacteria that inhabit the colon or large intestine break it down.',
  'One gram of digestible carbohydrates yields four kilocalories of energy for the cells in the body to perform work.',
  'In addition to providing energy and serving as building blocks for bigger macromolecules, carbohydrates are essential for the proper functioning of the nervous system, heart, and kidneys.',
  'As mentioned, glucose can be stored in the body for future use.',
  'In humans, the storage molecule of carbohydrates is called glycogen, and in plants, it is known as starch.',
  'Glycogen and starch are complex carbohydrates.',
  'INTRODUCTION | 5'],
 'sentence_count': 28}

In [12]:
#define splits size to chunks groups of sentences to chunks of sentence
splits_sentence_chunks = 10

def splits_sentence_to_chunks(input_list: list[str],chunk_size: int):
  return [input_list[i:i+chunk_size] for i in range(0,len(input_list),chunk_size)]  #here i =0,10,20 increases by multiple of 10 in each loop


for items in pages_and_text:
  items["sentence_chunks"] = splits_sentence_to_chunks(items["sentence"],splits_sentence_chunks)
  items["sentence_chunks_count"] = len(items["sentence_chunks"])

pages_and_text[20:24]

[{'page_number': 1,
  'page_character_count': 66,
  'page_word_count': 12,
  'page_sentence_count': 1,
  'text': 'PART I BASIC CONCEPTS IN NUTRITION BASIC CONCEPTS IN NUTRITION | 1',
  'sentence': ['PART I BASIC CONCEPTS IN NUTRITION BASIC CONCEPTS IN NUTRITION | 1'],
  'sentence_count': 1,
  'sentence_chunks': [['PART I BASIC CONCEPTS IN NUTRITION BASIC CONCEPTS IN NUTRITION | 1']],
  'sentence_chunks_count': 1},
 {'page_number': 2,
  'page_character_count': 31,
  'page_word_count': 6,
  'page_sentence_count': 1,
  'text': '2 | BASIC CONCEPTS IN NUTRITION',
  'sentence': ['2 | BASIC CONCEPTS IN NUTRITION'],
  'sentence_count': 1,
  'sentence_chunks': [['2 | BASIC CONCEPTS IN NUTRITION']],
  'sentence_chunks_count': 1},
 {'page_number': 3,
  'page_character_count': 353,
  'page_word_count': 60,
  'page_sentence_count': 4,
  'text': 'INTRODUCTION “If you’re hungry, you better eat what you know. If you’re from New Orleans and you get really hungry, you better have New Orleans food.” – Chef Leah Chase Seafood gumbo is made with a roux, shrimp, sausage, okra, celery, onion, and bell pepper, and then served over rice. (Source: Wikimedia Commons [New Tab], Kate, CC-BY) INTRODUCTION | 3',
  'sentence': ['INTRODUCTION “If you’re hungry, you better eat what you know.',
   'If you’re from New Orleans and you get really hungry, you better have New Orleans food.” –',
   'Chef Leah Chase Seafood gumbo is made with a roux, shrimp, sausage, okra, celery, onion, and bell pepper, and then served over rice. (',
   'Source: Wikimedia Commons [New Tab], Kate, CC-BY) INTRODUCTION | 3'],
  'sentence_count': 4,
  'sentence_chunks': [['INTRODUCTION “If you’re hungry, you better eat what you know.',
    'If you’re from New Orleans and you get really hungry, you better have New Orleans food.” –',
    'Chef Leah Chase Seafood gumbo is made with a roux, shrimp, sausage, okra, celery, onion, and bell pepper, and then served over rice. (',
    'Source: Wikimedia Commons [New Tab], Kate, CC-BY) INTRODUCTION | 3']],
  'sentence_chunks_count': 1},
 {'page_number': 4,
  'page_character_count': 1284,
  'page_word_count': 194,
  'page_sentence_count': 16,
  'text': 'Learning Objectives By the end of this chapter, you will be able to: • Define nutrition. • Describe basic concepts in nutrition. • Describe factors that affect your nutritional needs. • Describe the importance of research and scientific methods to understanding nutrition. • Discuss nutrition as a science. What are Nutrients? The foods we eat contain nutrients. Nutrients are substances required by the body to perform its basic functions. Nutrients must be obtained from our diet, since the human body does not synthesize or produce them. Nutrients have one or more of three basic functions: they provide energy, contribute to body structure, and/or regulate chemical processes in the body. These basic functions allow us to detect and respond to our environmental surroundings, move, excrete wastes, respire (breathe), grow, and reproduce. Six nutrients are required for the body to function and maintain overall health (Figure 1.1). These are carbohydrates, lipids, proteins, water, vitamins, and minerals. Foods also contain non-nutrients that may be harmful (such as natural toxins common in plant foods and additives like some dyes and preservatives) or beneficial (such as antioxidants). Figure 1.1 The six major nutrient classes Macronutrients Micronutrients 4 | INTRODUCTION',
  'sentence': ['Learning Objectives By the end of this chapter, you will be able to: • Define nutrition. •',
   'Describe basic concepts in nutrition. •',
   'Describe factors that affect your nutritional needs. •',
   'Describe the importance of research and scientific methods to understanding nutrition. •',
   'Discuss nutrition as a science.',
   'What are Nutrients?',
   'The foods we eat contain nutrients.',
   'Nutrients are substances required by the body to perform its basic functions.',
   'Nutrients must be obtained from our diet, since the human body does not synthesize or produce them.',
   'Nutrients have one or more of three basic functions: they provide energy, contribute to body structure, and/or regulate chemical processes in the body.',
   'These basic functions allow us to detect and respond to our environmental surroundings, move, excrete wastes, respire (breathe), grow, and reproduce.',
   'Six nutrients are required for the body to function and maintain overall health (Figure 1.1).',
   'These are carbohydrates, lipids, proteins, water, vitamins, and minerals.',
   'Foods also contain non-nutrients that may be harmful (such as natural toxins common in plant foods and additives like some dyes and preservatives) or beneficial (such as antioxidants).',
   'Figure 1.1 The six major nutrient classes Macronutrients Micronutrients 4 | INTRODUCTION'],
  'sentence_count': 15,
  'sentence_chunks': [['Learning Objectives By the end of this chapter, you will be able to: • Define nutrition. •',
    'Describe basic concepts in nutrition. •',
    'Describe factors that affect your nutritional needs. •',
    'Describe the importance of research and scientific methods to understanding nutrition. •',
    'Discuss nutrition as a science.',
    'What are Nutrients?',
    'The foods we eat contain nutrients.',
    'Nutrients are substances required by the body to perform its basic functions.',
    'Nutrients must be obtained from our diet, since the human body does not synthesize or produce them.',
    'Nutrients have one or more of three basic functions: they provide energy, contribute to body structure, and/or regulate chemical processes in the body.'],
   ['These basic functions allow us to detect and respond to our environmental surroundings, move, excrete wastes, respire (breathe), grow, and reproduce.',
    'Six nutrients are required for the body to function and maintain overall health (Figure 1.1).',
    'These are carbohydrates, lipids, proteins, water, vitamins, and minerals.',
    'Foods also contain non-nutrients that may be harmful (such as natural toxins common in plant foods and additives like some dyes and preservatives) or beneficial (such as antioxidants).',
    'Figure 1.1 The six major nutrient classes Macronutrients Micronutrients 4 | INTRODUCTION']],
  'sentence_chunks_count': 2}]

# Splitting each chunks into its own items.

Lets create a pages_and_chunks list where each sentence chunks are divided into pages_and_chunks and count its items respectivley.

In [13]:
import re

pages_and_chunks = []

for items in pages_and_text:
  for sentence in items["sentence_chunks"]:
    chunks_dict = {}
    chunks_dict["page_number"] = items["page_number"]
    joined_sentence = "".join(sentence).strip()
    joined_sentence = re.sub(r'\.([A-Z])',r'. \1',joined_sentence)


    chunks_dict["sentence_chunk"] = joined_sentence

    chunks_dict["chunk_char_count"] = len(joined_sentence)
    chunks_dict["chunk_word_count"] = len(joined_sentence.split())
    chunks_dict["chunk_token_count"] = len(joined_sentence)/4
    pages_and_chunks.append(chunks_dict)

In [14]:
pages_and_chunks[20:25]

[{'page_number': -1,
  'sentence_chunk': 'This page provides a record of changes made to this textbook. New editions are released when significant edits are made to the textbook. Revised editions are acknowledged with an e after the edition number (ex.2e). The exported files for this textbook reflect the most recent version. Table i. Human Nutrition OER Textbook Version History Version Date Details 1 June 4, 2018 Human Nutrition textbook published by the University of Hawai‘i at Mānoa’s Outreach College.2 August 27, 2020 Second edition of the Human Nutrition textbook published by the University of Hawai‘i at Mānoa’s Outreach College. •Added Health at Every Size section (Chapter 18) • Nutrition Facts Label section updated to reflect new guidelines (Chapter 12) • Major and Trace Minerals, Pregnancy and Infancy sections expanded (Chapters 10, 11, 13) • Embedded 176 learning activities created with the open source tool H5P ◦ Over 100 flashcards were added at the end of relevant sections ◦ Over 50 drag and drop activities were added to reinforce learning objectives 2e December 2021 Revised second edition of the Human Nutrition textbook published by the University of Hawai‘i at Mānoa’s Outreach College. •Added Accessibility Statement section • Added Version History • Reformatted learning activities, tables, and figures • Added new vocabulary words to the glossary • Updated US Dietary Guidelines Section (Chapters 12) Louisiana Edition January 2025 This Louisiana Edition published by LOUIS: The Louisiana Library Consortium • Reordered chapters • Removed Hawai‘i-specific content • Added content to reflect the unique food culture and nutritional issues in Louisiana VERSION HISTORY | XIX',
  'chunk_char_count': 1663,
  'chunk_word_count': 256,
  'chunk_token_count': 415.75},
 {'page_number': 0,
  'sentence_chunk': 'XX | VERSION HISTORY',
  'chunk_char_count': 20,
  'chunk_word_count': 4,
  'chunk_token_count': 5.0},
 {'page_number': 1,
  'sentence_chunk': 'PART I BASIC CONCEPTS IN NUTRITION BASIC CONCEPTS IN NUTRITION | 1',
  'chunk_char_count': 66,
  'chunk_word_count': 12,
  'chunk_token_count': 16.5},
 {'page_number': 2,
  'sentence_chunk': '2 | BASIC CONCEPTS IN NUTRITION',
  'chunk_char_count': 31,
  'chunk_word_count': 6,
  'chunk_token_count': 7.75},
 {'page_number': 3,
  'sentence_chunk': 'INTRODUCTION “If you’re hungry, you better eat what you know. If you’re from New Orleans and you get really hungry, you better have New Orleans food.” –Chef Leah Chase Seafood gumbo is made with a roux, shrimp, sausage, okra, celery, onion, and bell pepper, and then served over rice. (Source: Wikimedia Commons [New Tab], Kate, CC-BY) INTRODUCTION | 3',
  'chunk_char_count': 352,
  'chunk_word_count': 59,
  'chunk_token_count': 88.0}]

In [15]:
len(pages_and_chunks)

1752

In [16]:
import pandas as pd

df = pd.DataFrame(pages_and_chunks)
df.head(24)

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count
0,-19,Human Nutrition,15,2,3.75
1,-17,HUMAN NUTRITION Louisiana Edition MELISSA JOHN...,105,14,26.25
2,-16,Human Nutrition Copyright © 2022 by Melissa Jo...,238,30,59.50
3,-15,CONTENTS Preface xiii About the Contributors x...,518,79,129.50
4,-14,The Endocrine System 85 The Urinary System 89 ...,767,123,191.75
5,-13,Part V. Protein Introduction 219 Defining Prot...,646,93,161.50
6,-12,Part VIII. Water and Electrolytes Introduction...,559,80,139.75
7,-11,Magnesium 493 Summary of Major Minerals 497 Pa...,442,67,110.50
8,-10,Adolescence 648 Late Adolescence 652 Part XIV....,656,92,164.00
9,-9,Part XVII. Food Safety Introduction 773 The Ma...,636,97,159.00
10,-7,PREFACE “Food is an art form that nourishes bo...,594,88,148.50
11,-6,Faculty Charlene “Charlie” Shunick is an Assoc...,1309,199,327.25
12,-6,She earned her Ph. D. in Biochemistry from Tul...,1528,236,382.00
13,-6,Dr Yigiter had the opportunity to be invited t...,341,57,85.25
14,-5,believes the best and most painless treatment ...,1400,212,350.00
15,-5,She previously worked on a team to create both...,304,44,76.00
16,-4,Acknowledgements Contributors and Source Mater...,1878,280,469.50
17,-4,"If you are adopting this textbook, we would be...",117,22,29.25
18,-3,Special Thanks The efforts of Emily Frank and ...,471,72,117.75
19,-2,The LOUIS library consortium believes that edu...,1498,235,374.50
20,-1,This page provides a record of changes made to...,1663,256,415.75
21,0,XX | VERSION HISTORY,20,4,5.00
22,1,PART I BASIC CONCEPTS IN NUTRITION BASIC CONCE...,66,12,16.50
23,2,2 | BASIC CONCEPTS IN NUTRITION,31,6,7.75

In [17]:
min_chunk = min(chunk["chunk_token_count"] for chunk in pages_and_chunks)
max_chunk = max(chunk["chunk_token_count"] for chunk in pages_and_chunks)
print("min",min_chunk)
print("max",max_chunk)

min 2.5
max 653.0

In [18]:
import random
random.sample(pages_and_chunks,k=1)

[{'page_number': 24,
  'sentence_chunk': 'Vegan. This vegetarian diet does not include dairy, eggs, or any animal products or by-products. Practicing the Principles As Louisiana is known for its seafood and other meats, adopting a vegetarian or vegan diet may be an intimidating feat. However, it is not impossible!It’s time to put your chef’s hat on and 24 | LIFESTYLES AND NUTRITION',
  'chunk_char_count': 342,
  'chunk_word_count': 57,
  'chunk_token_count': 85.5}]

In [19]:
#Lets see the data(token chunks) that are above than 2000 and lower than 50

number_of_chunks = 0
for chunk in pages_and_chunks:
  if chunk["chunk_token_count"] > 500:
    number_of_chunks += 1
    print(chunk)
print(number_of_chunks)

{'page_number': 305, 'sentence_chunk': 'organizations were actively reinforcing strategies aimed at meeting the challenge of improving the health of all Americans. In 2010, the national campaign to reduce obesity was reinforced when First Lady Michelle Obama launched the “Let’s Move” initiative, which has the goal of “solving the challenge of childhood obesity within a generation so that children born today will reach adulthood at a healthy weight.”8 Another campaign, “Campaign to End Obesity,” was recently established to try to enable more Americans to eat healthy and be active by bringing together leaders from academia and industry, as well as public-health policy-makers, to create policies that will reverse the obesity trend and its associated diseases. The “Small-Change” Approach Currently, most people are not obese in this country. The gradual rise in overweight is happening because, on average, people consume slightly more calories daily than they expend, resulting in a gradual weight gain of one to two pounds a year. In 2003, the idea was first published that promoting small lifestyle changes to reduce weight gain occurring over time in all age groups may better reduce obesity rates in the American population.9 Scientific studies have demonstrated that asking people to increase the number of steps they take each day while providing them with pedometers that count the steps they take each day successfully prevents weight gain. A “small-changes” study published in the October 2007 issue of Pediatrics evaluated whether families that made two small lifestyle changes, which were to walk an additional two thousand steps per day and to eliminate 100 kilocalories per day from their typical diet by replacing dietary sugar with a noncaloric sweetener, would prevent weight gain in overweight children.10 The results of this study were that a higher percentage of children who made the small changes maintained or reduced their BMI in comparison to children of families given a pedometer but not asked to also make physical activity or dietary changes.11 Several more studies funded by the National Institutes of Health and USDA are ongoing and are evaluating the effectiveness of the “small- changes” approach in reducing weight gain.', 'chunk_char_count': 2221, 'chunk_word_count': 347, 'chunk_token_count': 555.25}
{'page_number': 465, 'sentence_chunk': 'Table 9.33 Some Phytochemical’s Obtained from Diet and Their Related Functions Phytochemical Phytochemical Source Phytochemical Function: Carotenoid Yellow-orange fruits, dark green leafy vegetables May possess strong cancer-fighting properties3 Indoles Cruciferous vegetables (i.e. bok choy, broccoli, choy sum) May inhibit the development of cancer-causing hormones and prevent tumor growth4 Phytoestrogen Grapes, berries, plums, soybeans, tofu, garlic May lower the risk for osteoporosis, heart disease, breast cancer, and menopausal symptoms5 Stanols Grains, nuts, legumes May lower blood cholesterol levels and reduce the risk of heart disease and stroke6 Saponins Broad beans, kidney beans, lentils May decrease blood lipids, lower cancer risks, and lower blood glucose responsefootnote]Shi, J., Arunasalam, K., Yeung, D., Kakuda, Y., Mittal, G., & Jiang, Y. (2004). Saponins from Edible Legumes: Chemistry, Processing, and Health Benefits. Journal of Medicinal Food, 7 (1): 67–78.https://doi.org/10.1089/109662004322984734. Accessed August 13, 2025. [/footnote] Terpenes Citrus fruits May slow cancer cell growth, aid in immune system support, and prevent virus related illness7 Flavonoids Fruits, vegetables, chocolates, wines, teas, nuts, seeds May benefit the immune system and prevent cancer cell growth.89 Anthocyanins Fruits and vegetables with vibrant colors of orange, red, purple, and blue May prevent cardiovascular disease, reduce cancer cell proliferation (growth/multiplication) and inhibit tumor formation.1011 Phenolic acids Coffee, fruits, vegetables, nuts, cereals, legumes, oilseeds, beverages and herbs May prevent cellular damage due to free-radical oxidation reaction and promote anti-inflammatory conditions in the body.12 3. Xu, D-P., Li, Y., Meng, X., Zhou, T., Zhou, Y., Zheng, J., Zhang, J.-J., & Li, H.-B. (2017). Natural Antioxidants in Foods and Medicinal Plants: Extraction, Assessment and Resources. International Journal of Molecular Sciences, 18 (1): 96.https://doi.org/10.3390/ijms18010096. Accessed August 13, 2025 4.', 'chunk_char_count': 2059, 'chunk_word_count': 271, 'chunk_token_count': 514.75}
{'page_number': 582, 'sentence_chunk': 'A. Legislative findings and declarations. (1) The Legislature of Louisiana hereby finds that the surgeon general of the United States recommends that babies from birth to one year of age be breastfed, unless medically contraindicated, for the babies to attain an optimal healthy start in life, but that despite that recommendation, statistics reveal a declining percentage of mothers who are now choosing to breastfeed their babies, and nearly half of all new mothers are choosing formula over breastfeeding before they even leave the hospital. (2) The legislature further finds that breast milk provides better nutrition and more immunity to disease, is easier for babies to digest, and may raise a baby’s intelligence quotient, but that the social constraints of modern society work against the choice of breastfeeding and lead new mothers with demanding time schedules to opt for formula feeding for reasons such as embarrassment and the fear of social ostracism or criminal prosecution. (3) The legislature does hereby declare that the promotion of family values and infant health demands that our society put an end to the vicious cycle of embarrassment and ignorance that constricts women and men alike on the subject of breastfeeding, and that in a genuine effort to promote family values, our society should encourage public acceptance of this most basic act of nurture between mother and baby and should take appropriate steps to ensure that no mother is made to feel incriminated or socially ostracized for breastfeeding her baby. B. Right to breastfeed. Notwithstanding any other provision of law to the contrary, a mother may breastfeed her baby in any place of public accommodation, resort, or amusement. C. “Discriminatory practice in connection with public accommodations” to include a discriminatory practice against a mother breastfeeding her baby. Any direct or indirect act or practice of exclusion, distinction, restriction, segregation, limitation, refusal, denial, or any other act or practice of differentiation or preference in the treatment of a mother breastfeeding her baby shall be a “discriminatory practice in connection with public accommodations” for this Chapter. D. Breastfeeding; discriminatory practices prohibited. It is a discriminatory practice in connection with public accommodations for a person to deny an individual the full and equal enjoyment of the goods, services, facilities, privileges, advantages, and accommodations of a place of public accommodation, resort, or amusement, as defined in this Chapter, because the individual is a mother breastfeeding her baby.', 'chunk_char_count': 2612, 'chunk_word_count': 397, 'chunk_token_count': 653.0}
{'page_number': 618, 'sentence_chunk': 'Table 12.7 Serving Sizes for Toddlers Food Group Daily Serving Examples Grains About 3-5 ounces of grains per day, ideally whole grains • 3 slices of bread • 1 slice of bread, plus ⅓ cup of cereal, and ¼ cup of cooked whole-grain rice or pasta Proteins 2-4 ounces of meat, poultry, fish, eggs, or legumes • 1 ounce of lean meat or chicken, plus one egg • 1 ounce of fish, plus ¼ cup of cooked beans Fruits 1-1.5 cups of fresh, frozen, canned, and/ or dried fruits, or 100 percent fruit juice • 1 small apple cut into slices • 1 cup of sliced or cubed fruit • 1 large banana Vegetables 1-1.5 cups of raw and/or cooked vegetables • 1 cup of pureed, mashed, or finely chopped vegetables (such as sweet potato, chopped broccoli, or tomato sauce) Dairy Products 2-2.5 cups per day • 2 cups of fat-free or low-fat milk • 1 cup of fat-free or low-fat milk, plus two slices of cheese • 1 cup of fat-free or low-fat milk, plus 1 cup of yogurt Macronutrients For carbohydrate intake, the Acceptable Macronutrient Distribution Range (AMDR) is 45 to 65 percent of daily calories (113 to 163 grams for 1,000 daily calories). Toddlers’ needs increase to support their body and brain development. The RDA of protein is 5 to 20 percent of daily calories (13 to 50 grams for 1,000 daily calories). The AMDR for fat for toddlers is 30 to 40 percent of daily calories (33 to 44 grams for 1,000 daily calories). Essential fatty acids, along with nerve and other tissue types, are vital for the development of the eyes. However, toddlers should not consume foods with high amounts of trans fats and saturated fats. Instead, young children require the equivalent of 3 teaspoons of healthy oils, such as extra virgin cold-pressed olive oil, each day. Due to toddlers’ relatively high nutrient needs, a healthy dietary pattern has virtually no room for added sugars. Toddlers consume more than 100 calories from added sugars daily, ranging from 40 to 250 calories a day (about 2.5 to 16 teaspoons). Sugar, sweetened beverages, particularly fruit drinks, contribute more than 618 | TODDLER YEARS', 'chunk_char_count': 2070, 'chunk_word_count': 366, 'chunk_token_count': 517.5}
{'page_number': 824, 'sentence_chunk': 'Table 18.1 The Pros and Cons of Seven Popular Diets Diet Pros Cons DASH Diet • Recommended by the National Heart, Lung, and Blood Institute, the American Heart Association, and many physicians • Helps to lower blood pressure and cholesterol • Reduces risk of heart disease and stroke • Reduces risk of certain cancers • Reduces diabetes risk • There are very few negative factors associated with the DASH diet • Risk for hyponatremia Gluten-Free Diet • Reduces the symptoms of gluten intolerance, such as chronic diarrhea, cramping, constipation, and bloating • Promotes healing of the small intestines for people with celiac disease, preventing malnutrition • May be beneficial for other autoimmune diseases, such as Parkinson’s disease, rheumatoid arthritis, and multiple sclerosis • Risk of folate, iron, thiamin, riboflavin, niacin, and vitamin B6 deficiencies • Special gluten-free products can be hard to find and expensive • Requires constant vigilance and careful food label reading, since gluten is found in many products Low-Carb Diet • Restricts refined carbohydrates, such as white flour and white sugar • May temporarily improve blood sugar or blood cholesterol levels • Not entirely evidence-based • Results in higher fat and protein consumption • Does not meet the RDA for carbohydrates to provide glucose to the brain Macrobiotic Diet • Low in saturated fats and high in fiber • Emphasizes whole foods and de-emphasizes processed foods • Rich in phytoestrogens, which may reduce the risk of estrogen-related cancers • Not entirely evidence-based • Lacks certain vitamins and minerals; supplements are often required • Can result in a very low caloric intake • Lack of energy may result from inadequate protein Mediterranean Diet • A reduced risk of cardiovascular disease and mortality • A lower risk of cancer • De-emphasizes processed foods and emphasizes whole foods and healthy fats • Lower sodium intake, due to fewer processed foods • Emphasis on monosaturated fats leads to lower cholesterol • Highlighting fruits and vegetables raises consumption of antioxidants • Does not specify daily serving amounts • Potential for high fat and high calorie intake as nuts and oils are calorie-dense foods • Drinking one to two glasses of wine per day may not be healthy for those with certain conditions 824 | COMPARING DIETS', 'chunk_char_count': 2338, 'chunk_word_count': 374, 'chunk_token_count': 584.5}
5

Now filter the token less than 30 and more than 500.Since less than 30 are more like headings,intro and references.And more than 500 too large and topics mixed.

In [20]:
filtered_chunks = []

for chunk in pages_and_chunks:
  if 30<= chunk["chunk_token_count"] <= 500:
    filtered_chunks.append(chunk)

print(len(pages_and_chunks))
print(len(filtered_chunks))

1752
1571

In [21]:
#Now lets see the chunks
import random
random.sample(filtered_chunks,k=1)

[{'page_number': 147,
  'sentence_chunk': 'fiber meal as compared to a low-fiber meal (see Figure 4.14 “Fibers Role in Carbohydrate Digestion and Absorption”) can significantly slow down the absorption process, therefore affecting blood glucose levels. Americans typically do not consume the recommended amount of whole grains, which is 50 percent or more of grains from whole grains. Figure 3.14 Fibers Role in Carbohydrate Digestion and Absorption (Source: University of Hawaii @ Manoa [New Tab], Allison Calabrese, CC-BY-NC-SA) Diets high in whole grains have repeatedly been shown to decrease weight. A large group of studies all support that consuming more than two servings of whole grains per day reduces one’s chances of getting Type 2 diabetes by 21 percent.7 The Nurses’ Health Study found that women who consumed two to three servings of whole grain products daily were 30 percent less likely to have a heart attack.8 7.de Munter, J. S., Hu, F. B., et al. (2007). Whole Grain, Bran, and Germ Intake and Risk of Type 2 Diabetes: A Prospective Cohort Study and Systematic Review. PLOS Medicine, 4(8), e261.',
  'chunk_char_count': 1072,
  'chunk_word_count': 174,
  'chunk_token_count': 268.0}]

Now,Lets Embeddings the filterd chunks we prepare earlier.So, to embeds use the all-mpnet-base-v2 from the hugging face transformer.

In [22]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.3.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.8.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.5.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)

In [23]:
from sentence_transformers import SentenceTransformer

#load pre-trained embedding model
model = SentenceTransformer("all-mpnet-base-v2")

#prepare sentence or chunks take one example
sentences = [
    "Human Nutrition textbook published by University of Hawai‘i at Mānoa.",
    "This chapter explains vitamins and minerals.",
    "Seafood gumbo is made with roux, shrimp, and vegetables."
]

#Encode sentence into embeddings
embeddings = model.encode(sentence)
print(embeddings.shape)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

(8, 768)

In [24]:
print(embeddings)

[[ 0.08436868  0.02907833  0.07351795 ... -0.02596605 -0.00244565
  -0.01972943]
 [-0.01307861  0.0561556  -0.0083619  ... -0.03817027  0.04548811
  -0.01025813]
 [ 0.05974299 -0.12097659  0.00187955 ...  0.01324266  0.01763458
  -0.00459644]
 ...
 [ 0.07914154 -0.02192187 -0.0376835  ... -0.03706811 -0.05492734
  -0.07540243]
 [ 0.02323637  0.01840339 -0.02880682 ... -0.03250247  0.01334669
  -0.06288543]
 [ 0.05605077 -0.01007421 -0.02405846 ... -0.01976281 -0.05055379
  -0.03034719]]

Lets use embeddings into our filtered chunks

In [25]:

model.to("cuda")

#Embed each chunk one by one
for chunk in filtered_chunks:
  chunk["chunk_embedding"] = model.encode(chunk["sentence_chunk"])

In [26]:
filtered_chunks[20]

{'page_number': 4,
 'sentence_chunk': 'These basic functions allow us to detect and respond to our environmental surroundings, move, excrete wastes, respire (breathe), grow, and reproduce. Six nutrients are required for the body to function and maintain overall health (Figure 1.1). These are carbohydrates, lipids, proteins, water, vitamins, and minerals. Foods also contain non-nutrients that may be harmful (such as natural toxins common in plant foods and additives like some dyes and preservatives) or beneficial (such as antioxidants). Figure 1.1 The six major nutrient classes Macronutrients Micronutrients 4 | INTRODUCTION',
 'chunk_char_count': 591,
 'chunk_word_count': 85,
 'chunk_token_count': 147.75,
 'chunk_embedding': array([ 4.54076454e-02,  1.89694623e-03,  7.00056646e-03,  1.68529134e-02,
         5.35846166e-02,  2.83740461e-02, -4.59137633e-02,  1.89810954e-02,
         4.91336882e-02, -6.71576485e-02, -5.17519191e-03,  1.17862510e-04,
         1.48754893e-02,  1.01096407e-02,  2.49246303e-02, -3.28671187e-02,
         2.86920071e-02, -2.65474082e-03, -5.97183444e-02,  8.16121046e-03,
        -4.43468466e-02,  2.08265204e-02,  3.29986238e-03, -3.02910600e-02,
        -5.07658198e-02,  6.42469078e-02,  3.00101656e-02,  1.75100379e-02,
         7.10028317e-03, -1.38480198e-02, -3.90917808e-02,  9.67534166e-03,
         5.04591689e-03, -8.57088044e-02,  2.37906829e-06, -1.54455527e-04,
        -5.06040342e-02, -7.14792265e-03, -4.49650697e-02, -1.32022407e-02,
         1.88651178e-02, -2.36057863e-02, -4.76496341e-03, -2.05519004e-03,
         5.12498543e-02,  9.23947897e-03,  1.00102508e-02,  5.88253774e-02,
         1.39401918e-02,  2.00316161e-02,  1.56564396e-02,  2.60925796e-02,
         3.28955986e-03,  5.68629336e-03, -3.97534408e-02,  6.24793507e-02,
         2.54823454e-02,  7.58227780e-02,  2.04025675e-02,  4.88219969e-03,
         1.13502378e-02,  3.19956094e-02,  2.42065024e-02,  3.92090119e-02,
         1.72722153e-02,  6.85366914e-02, -1.80027690e-02, -3.96187454e-02,
         4.53597419e-02,  6.92219958e-02, -5.80229834e-02,  1.29484916e-02,
         3.63732763e-02, -1.99361164e-02, -1.54442945e-02, -5.32287732e-03,
        -1.52711349e-03,  1.76280027e-03,  3.40991057e-02,  1.48845837e-02,
         2.90655252e-02, -1.76189058e-02,  2.10163724e-02, -2.83948565e-03,
         5.48665896e-02, -2.59105898e-02, -2.54533961e-02, -8.37853458e-03,
        -3.16982381e-02, -5.69250360e-02, -9.76315141e-02, -1.29133426e-02,
         2.15286165e-02,  2.31063161e-02,  6.04925565e-02, -1.10863922e-02,
         1.64776184e-02,  5.16578183e-02,  9.14864242e-02, -8.38484988e-03,
        -3.70826200e-02,  6.19282888e-04, -7.09193796e-02, -2.31529791e-02,
        -1.20453965e-02, -4.77105752e-02,  9.32759419e-03,  1.07723661e-02,
        -4.75090109e-02,  1.87908881e-03, -2.21708650e-03, -1.21101867e-02,
        -1.83942728e-02,  1.02916658e-01, -1.58299021e-02,  1.14186797e-02,
         1.55340517e-02, -1.56702958e-02,  2.77546700e-02, -1.60810761e-02,
        -2.19598413e-02,  3.95727754e-02,  3.92388254e-02, -6.99669356e-03,
         1.56339328e-03, -5.69539191e-03,  1.88390464e-02, -4.19665724e-02,
        -1.76507067e-02, -4.23020273e-02, -2.83937268e-02, -2.51427311e-02,
        -1.58242113e-03,  2.43569482e-02, -2.21056081e-02, -4.99578984e-03,
         5.39554507e-02, -1.90432332e-02, -2.51918249e-02, -4.90922146e-02,
        -3.89286019e-02, -4.84168604e-02, -6.71147406e-02,  2.86444202e-02,
        -4.95669991e-03, -7.18418928e-03,  5.81470467e-02,  5.64977862e-02,
         4.92595658e-02,  2.47696564e-02,  3.03192763e-03, -2.77651958e-02,
         4.13549840e-02, -1.20399641e-02,  7.42991790e-02, -1.35796266e-02,
         7.11235031e-02, -5.48995808e-02, -3.11982967e-02, -3.08649894e-02,
        -7.37067871e-03, -3.44209261e-02, -6.05348460e-02, -3.03507447e-02,
         3.60513851e-03,  4.75049237e-05,  8.71245414e-02, -6.68106973e-03,
        -1.18361469e-02, -7.87760946e-04, -3.64628062e-02, -3.77656780e-02,
        -3.43510620e-02, -2.53192540e-02,  3.61833684e-02,  6.17132299e-02,
         3.41439769e-02,  3.78599614e-02,  4.43430059e-03,  1.72613766e-02,
         3.54346596e-02,  4.93033510e-03, -6.58063665e-02,  5.31861261e-02,
        -2.20025387e-02, -1.99445132e-02, -5.48832379e-02, -2.10809167e-02,
         2.45836638e-02, -4.43354063e-03,  6.08456694e-02,  2.33136956e-02,
         2.71267239e-02, -5.95658720e-02,  2.94879004e-02, -2.09124740e-02,
        -1.31075568e-02, -5.70901707e-02, -1.56560577e-02, -5.58876023e-02,
         4.33932766e-02,  7.67812878e-02, -1.16010252e-02, -7.90586136e-03,
        -4.68696095e-02,  2.64030173e-02,  1.04973163e-03,  2.32616588e-02,
         6.64473549e-02, -1.85325556e-02,  8.61637015e-03, -2.98851822e-02,
         2.40402587e-04, -2.60380600e-02, -3.65017517e-03, -6.67269900e-02,
        -3.20131239e-03, -4.48767059e-02, -7.00536743e-02, -3.74730304e-02,
         2.97501609e-02,  1.12290895e-02, -9.43303779e-02, -5.41700870e-02,
         4.61304784e-02,  2.85688564e-02,  1.00293104e-02,  1.70273408e-02,
        -6.13987520e-02,  3.99551541e-03,  5.01295775e-02,  4.62964550e-02,
        -4.33780663e-02, -7.41339568e-03,  1.85000543e-02, -4.31057587e-02,
         4.97589493e-03,  4.87574749e-02, -1.32053066e-02,  8.03373456e-02,
        -5.53255016e-03,  7.75789171e-02,  8.90572090e-03, -1.94245297e-02,
        -3.45171355e-02,  2.18374655e-02, -5.57869300e-02, -4.56532836e-02,
        -4.73749451e-02,  4.56115194e-02,  1.52120106e-02,  1.20089669e-02,
        -2.87366882e-02, -2.21833009e-02, -9.07108840e-03, -3.35765607e-03,
         3.45096923e-02,  2.94118263e-02, -6.25079870e-02,  8.45474750e-03,
        -2.49420665e-03, -3.57449451e-03,  3.09051666e-02,  1.27304718e-02,
        -1.77135635e-02, -7.41260126e-03,  4.44659851e-02,  4.15507238e-03,
        -3.07788812e-02, -3.58705819e-02,  2.75991228e-03,  3.59020717e-02,
         2.21077744e-02,  3.58387083e-02, -3.04509569e-02,  2.00572908e-02,
         5.93466088e-02, -1.59045905e-02, -1.50884753e-02,  8.88943020e-03,
        -3.27187665e-02, -4.06331802e-03,  3.08308918e-02,  4.00403701e-02,
        -2.02481374e-02, -1.40355900e-02, -5.47539163e-03,  7.17532029e-03,
         1.19736165e-01, -3.62515002e-02,  6.42439052e-02,  2.29855906e-02,
        -6.35043439e-03, -1.65890083e-02, -2.53059175e-02,  2.70037986e-02,
         1.43976407e-02, -4.73149084e-02,  2.21416485e-02, -3.15123200e-02,
        -2.53020078e-02,  1.80804376e-02, -4.59879339e-02,  2.64816694e-02,
        -8.70650727e-03,  9.76011530e-02,  7.76276272e-03, -2.56150812e-02,
         7.06861094e-02,  3.39592546e-02,  6.25723833e-03, -1.88163726e-03,
        -3.44090573e-02, -1.68013126e-02, -2.78100390e-02,  2.46254075e-03,
        -4.51456103e-03,  5.63729741e-02,  1.22595206e-02, -3.41589376e-02,
         5.23287570e-03, -1.13826040e-02, -2.32582297e-02, -1.45940399e-02,
        -1.49204386e-02, -4.37977025e-03, -3.37206293e-03,  4.11085300e-02,
        -1.07958868e-01,  7.18286401e-03, -2.38329154e-02,  3.60132568e-02,
        -4.62859077e-03, -1.93626713e-02,  4.88091670e-02,  1.56423412e-02,
        -1.11018065e-02, -1.62083656e-02, -2.44547334e-03, -1.05321333e-02,
        -2.46735085e-02, -2.43203454e-02, -1.46170612e-02,  4.43782955e-02,
         4.43086997e-02,  5.26359044e-02, -2.78747324e-02,  1.29626356e-02,
         1.78666948e-03,  1.56889074e-02, -1.54328495e-02, -4.18488979e-02,
         2.52598841e-02,  4.52068038e-02,  2.46501416e-02,  3.16305533e-02,
         7.10052252e-03,  1.14610707e-02, -4.78257388e-02, -3.60581204e-02,
         3.74810882e-02,  1.41311716e-02, -7.20168501e-02, -2.38940073e-03,
         6.69050291e-02, -3.01843346e-03, -1.05348667e-02,  2.35011093e-02,
        -4.11931723e-02, -2.36530025e-02,  1.63777880e-02,  1.35524254e-02,
        -3.54034156e-02, -1.23759266e-02, -1.87597163e-02,  3.91803794e-02,
         1.44284414e-02,  2.49040890e-02, -1.72954574e-01, -9.83892009e-04,
         2.52801869e-02,  2.10636985e-02,  4.01036441e-02, -1.05869174e-02,
         2.35349257e-02,  6.69779349e-03, -2.77149044e-02, -2.75321957e-02,
         7.44563490e-02, -4.00994271e-02, -1.36132492e-02, -6.99054599e-02,
        -9.30027291e-02,  7.00988695e-02,  1.07401693e-02, -2.82062776e-02,
        -7.33548449e-03,  1.83419157e-02, -1.25562353e-02, -2.73233838e-03,
         4.10153642e-02, -8.87754336e-02, -1.83404628e-02, -3.94786112e-02,
         3.92753072e-02, -8.11364222e-03,  2.24915594e-02, -2.57257819e-02,
         4.18769158e-02,  4.64108512e-02,  5.19251414e-02, -6.01024218e-02,
        -2.66574090e-03, -2.19079014e-02,  6.04801364e-02,  1.30348199e-03,
         1.29754534e-02, -3.69949751e-02,  4.45672609e-02, -2.88759936e-02,
        -5.43052405e-02, -7.08646774e-02, -1.36407027e-02, -3.72607989e-04,
        -7.32007176e-02, -4.61917138e-03,  2.38436423e-02,  2.77637467e-02,
        -2.67308690e-02,  1.75930262e-02, -4.06009890e-03, -2.07943395e-02,
         7.00329896e-03, -7.87166692e-03, -1.04425900e-01,  4.52974346e-03,
         5.11519089e-02, -8.07196051e-02, -4.43153642e-03,  6.15823548e-03,
         1.98963787e-02,  3.92914899e-02, -9.61117214e-04, -2.54999045e-02,
        -3.47475335e-02,  7.03181233e-03, -2.69194487e-02, -1.69504061e-02,
         3.90607305e-02,  3.96893583e-02, -1.15065053e-02,  3.08157597e-02,
        -4.61716726e-02,  6.25688285e-02, -4.73338589e-02,  1.75378304e-02,
        -2.96258647e-02, -3.26116905e-02,  6.22645430e-02, -4.66607846e-02,
        -5.37592859e-04, -3.63054387e-02, -3.05198859e-02, -3.01087145e-02,
        -6.25395775e-02,  8.94151535e-03,  2.91859694e-02, -4.43514772e-02,
        -2.76823062e-02,  5.15704416e-03, -5.17318211e-03, -3.19273886e-03,
         1.01157166e-02, -9.20995884e-03,  4.46263291e-02, -2.20882706e-02,
         1.61266923e-02,  3.22458558e-02,  4.65328954e-02,  7.54497051e-02,
         2.51810886e-02, -5.29184705e-03,  2.76466608e-02,  4.56354767e-02,
        -1.56152165e-02, -2.91280113e-02,  3.00519038e-02, -9.23642609e-03,
        -8.99608596e-04,  5.49610816e-02,  6.33653626e-02,  6.11456037e-02,
         9.83827561e-03, -2.68665086e-02,  3.42543935e-03,  5.51327467e-02,
         2.55535468e-02, -7.46048661e-03,  4.11194526e-02, -2.79377811e-02,
         3.81351039e-02, -2.04492342e-02, -2.74099093e-02, -1.71013419e-02,
        -7.07680034e-03,  1.43027017e-02, -1.55279776e-02, -1.12146633e-02,
        -6.97339699e-03,  4.36059060e-03, -1.92047749e-02, -1.34587530e-02,
         2.00915858e-02,  4.60034385e-02, -8.37116763e-02, -6.15602359e-02,
        -7.88210519e-03,  9.95510630e-03, -1.51944701e-02, -7.06490083e-03,
         1.67189799e-02, -5.35898097e-02, -2.06918642e-02,  4.09716405e-02,
         3.67656909e-02, -1.33691467e-02,  9.15696099e-03,  1.50164319e-02,
        -6.12661466e-02,  3.56326438e-02,  6.29942492e-03, -1.36156902e-02,
        -3.03136720e-03,  2.30114441e-02, -1.19657465e-03,  4.84660678e-02,
        -7.00865909e-02,  1.22709133e-01, -3.80292088e-02,  2.81094331e-02,
         6.12668786e-03, -2.77831894e-03, -1.06535256e-02,  1.11843124e-02,
         4.85694520e-02,  5.76530360e-02, -6.15284964e-02, -6.40278086e-02,
         6.43921318e-03, -4.05426845e-02, -2.61125863e-02, -1.00135887e-02,
        -5.46353757e-02,  4.35969065e-04,  6.83493465e-02, -6.06436985e-33,
         7.57546499e-02, -3.05674877e-02,  3.24210599e-02,  8.29070881e-02,
         3.03982776e-02,  3.96926440e-02,  2.26078033e-02, -3.95554602e-02,
        -3.86837013e-02, -1.39100263e-02,  5.16629890e-02,  3.70578803e-02,
        -1.02912858e-02, -1.18740499e-02,  4.72048819e-02, -7.41893239e-03,
        -2.12825718e-03, -3.15144546e-02, -2.47170441e-02, -1.08147692e-02,
        -1.27646336e-02, -8.23110249e-03,  4.27983291e-02, -1.10778334e-02,
         7.13275094e-03,  8.49806517e-03,  1.28303689e-03,  1.39011664e-03,
        -5.44413552e-02,  3.10340244e-02, -3.18006650e-02,  7.48087391e-02,
         1.96849331e-02, -9.09730792e-03, -2.44509950e-02, -3.96767072e-03,
        -6.18227646e-02, -2.49513742e-02,  4.70657088e-02, -3.02144373e-03,
        -8.23482126e-02, -1.97013337e-02, -2.44931951e-02, -8.18550028e-03,
         1.92003767e-03, -1.08173573e-02, -3.75896133e-02, -1.56276040e-02,
         6.01361208e-02,  5.89428004e-03,  5.30908257e-02,  1.41651677e-02,
         1.08135352e-03,  1.61254965e-02, -4.34924709e-03,  9.39178318e-02,
        -1.59259755e-02, -1.10457269e-02,  7.70503357e-02,  2.35534310e-02,
        -1.88287420e-04,  4.77019139e-02, -2.10514069e-02,  5.61820827e-02,
         1.17410561e-02, -2.74844025e-03, -4.05146219e-02,  6.24433684e-04,
        -4.36553173e-02,  3.69761046e-03,  1.42329559e-02, -1.18728559e-02,
        -6.27075229e-03,  5.31825889e-03, -1.80538874e-02,  6.13629958e-03,
        -1.09005747e-02,  2.69747991e-02, -2.97138579e-02, -2.81710997e-02,
        -4.60656807e-02, -2.31188834e-02,  2.85939313e-02, -1.44087467e-02,
         2.35535093e-02, -1.82734951e-02, -1.06843014e-04,  8.15778913e-04,
         4.32776695e-04, -5.95292449e-03, -2.96170022e-02,  4.94357012e-02,
         9.37787630e-03, -2.33882423e-02,  2.65917871e-02,  1.32572846e-02,
         1.50665222e-02, -5.12312613e-02,  3.15048685e-03, -3.00020911e-02,
        -5.30707128e-02,  1.04167098e-02,  2.62226183e-02, -1.05523327e-02,
        -2.06504744e-02, -1.23151559e-02, -5.35088107e-02,  6.18501380e-03,
         6.12211674e-02, -7.02657625e-02,  1.78306531e-02, -6.94011245e-03,
         4.31273989e-02, -1.26163242e-02, -2.69225147e-02, -9.68912136e-05,
         1.13576986e-02,  4.68192846e-02, -3.14691216e-02,  4.35808860e-03,
        -2.23797858e-02,  5.45599535e-02,  2.01436952e-02, -5.23962304e-02,
         1.74206514e-02, -6.46863431e-02,  3.74056734e-02,  1.61539968e-02,
         2.90668495e-02,  4.78173159e-02,  2.87447358e-03,  3.75155583e-02,
         3.10227392e-07,  4.02397811e-02, -2.50707544e-05, -6.84077200e-03,
        -1.01641797e-01, -2.61035096e-02, -2.88203452e-02,  3.63503359e-02,
        -1.92267634e-02, -5.89412078e-02,  3.85047495e-02,  6.39052540e-02,
        -6.47015348e-02,  1.38535618e-03,  1.53819956e-02, -6.93994993e-03,
        -3.88770783e-03, -1.81144290e-02, -7.43515715e-02,  2.74030715e-02,
        -2.76369844e-02, -5.92659554e-03, -1.98280551e-02, -5.56436777e-02,
         1.40246423e-02, -3.79512608e-02, -7.89788610e-04,  1.04486402e-02,
        -2.64303219e-02,  3.37026194e-02,  1.50616691e-02,  4.28380407e-02,
         1.57627426e-02,  9.79883689e-03,  1.53753711e-02, -3.33201401e-02,
         5.90003189e-03,  9.48535837e-03, -4.73081740e-03, -1.18605997e-02,
         7.64809316e-03, -5.52949980e-02,  2.28903461e-02,  2.53808107e-02,
         5.83030051e-03, -4.11727391e-02, -8.19856226e-02, -1.85285639e-02,
        -5.92563255e-03,  2.00557951e-02,  1.55708231e-02, -3.36350948e-02,
         4.23976313e-03, -2.66684350e-02, -7.95845874e-03, -2.82549504e-02,
         6.77174469e-03,  3.58391441e-02,  1.26934964e-02,  1.46070505e-02,
         5.72281927e-02, -5.86738251e-03, -2.22217944e-02, -3.54155758e-03,
        -3.96689177e-02,  2.36860793e-02,  2.07861271e-02, -9.29503050e-03,
         2.42163385e-34, -1.47538176e-02, -2.15335209e-02,  7.01478682e-03,
        -2.77185235e-02, -2.82506142e-02,  1.46436738e-02, -8.52297172e-02,
         1.30032767e-02, -1.55456048e-02, -2.38443259e-02, -7.36369868e-04],
       dtype=float32)}

In [27]:
text_chunks = [chunks["sentence_chunk"] for chunks in filtered_chunks]

text_chunks[20]

'These basic functions allow us to detect and respond to our environmental surroundings, move, excrete wastes, respire (breathe), grow, and reproduce. Six nutrients are required for the body to function and maintain overall health (Figure 1.1). These are carbohydrates, lipids, proteins, water, vitamins, and minerals. Foods also contain non-nutrients that may be harmful (such as natural toxins common in plant foods and additives like some dyes and preservatives) or beneficial (such as antioxidants). Figure 1.1 The six major nutrient classes Macronutrients Micronutrients 4 | INTRODUCTION'

In [28]:
#only embeddings of text
text_chunks_embeddings = model.encode(
    text_chunks,
    batch_size = 32,
    convert_to_tensor= True
)

In [29]:
text_chunks_embeddings.shape

torch.Size([1571, 768])

In [30]:
text_chunks_embeddings[20]

tensor([ 4.5408e-02,  1.8969e-03,  7.0005e-03,  1.6853e-02,  5.3585e-02,
         2.8374e-02, -4.5914e-02,  1.8981e-02,  4.9134e-02, -6.7158e-02,
        -5.1751e-03,  1.1791e-04,  1.4876e-02,  1.0110e-02,  2.4925e-02,
        -3.2867e-02,  2.8692e-02, -2.6547e-03, -5.9718e-02,  8.1612e-03,
        -4.4347e-02,  2.0827e-02,  3.2999e-03, -3.0291e-02, -5.0766e-02,
         6.4247e-02,  3.0010e-02,  1.7510e-02,  7.1003e-03, -1.3848e-02,
        -3.9092e-02,  9.6753e-03,  5.0459e-03, -8.5709e-02,  2.3791e-06,
        -1.5444e-04, -5.0604e-02, -7.1479e-03, -4.4965e-02, -1.3202e-02,
         1.8865e-02, -2.3606e-02, -4.7650e-03, -2.0552e-03,  5.1250e-02,
         9.2395e-03,  1.0010e-02,  5.8825e-02,  1.3940e-02,  2.0032e-02,
         1.5656e-02,  2.6093e-02,  3.2896e-03,  5.6863e-03, -3.9753e-02,
         6.2479e-02,  2.5482e-02,  7.5823e-02,  2.0403e-02,  4.8822e-03,
         1.1350e-02,  3.1996e-02,  2.4207e-02,  3.9209e-02,  1.7272e-02,
         6.8537e-02, -1.8003e-02, -3.9619e-02,  4.5360e-02,  6.9222e-02,
        -5.8023e-02,  1.2948e-02,  3.6373e-02, -1.9936e-02, -1.5444e-02,
        -5.3228e-03, -1.5271e-03,  1.7628e-03,  3.4099e-02,  1.4885e-02,
         2.9066e-02, -1.7619e-02,  2.1016e-02, -2.8395e-03,  5.4867e-02,
        -2.5911e-02, -2.5453e-02, -8.3785e-03, -3.1698e-02, -5.6925e-02,
        -9.7631e-02, -1.2913e-02,  2.1529e-02,  2.3106e-02,  6.0493e-02,
        -1.1086e-02,  1.6478e-02,  5.1658e-02,  9.1486e-02, -8.3848e-03,
        -3.7083e-02,  6.1928e-04, -7.0919e-02, -2.3153e-02, -1.2045e-02,
        -4.7711e-02,  9.3276e-03,  1.0772e-02, -4.7509e-02,  1.8791e-03,
        -2.2171e-03, -1.2110e-02, -1.8394e-02,  1.0292e-01, -1.5830e-02,
         1.1419e-02,  1.5534e-02, -1.5670e-02,  2.7755e-02, -1.6081e-02,
        -2.1960e-02,  3.9573e-02,  3.9239e-02, -6.9967e-03,  1.5634e-03,
        -5.6954e-03,  1.8839e-02, -4.1967e-02, -1.7651e-02, -4.2302e-02,
        -2.8394e-02, -2.5143e-02, -1.5824e-03,  2.4357e-02, -2.2106e-02,
        -4.9958e-03,  5.3955e-02, -1.9043e-02, -2.5192e-02, -4.9092e-02,
        -3.8929e-02, -4.8417e-02, -6.7115e-02,  2.8644e-02, -4.9567e-03,
        -7.1842e-03,  5.8147e-02,  5.6498e-02,  4.9260e-02,  2.4770e-02,
         3.0319e-03, -2.7765e-02,  4.1355e-02, -1.2040e-02,  7.4299e-02,
        -1.3580e-02,  7.1124e-02, -5.4900e-02, -3.1198e-02, -3.0865e-02,
        -7.3707e-03, -3.4421e-02, -6.0535e-02, -3.0351e-02,  3.6051e-03,
         4.7527e-05,  8.7125e-02, -6.6811e-03, -1.1836e-02, -7.8780e-04,
        -3.6463e-02, -3.7766e-02, -3.4351e-02, -2.5319e-02,  3.6183e-02,
         6.1713e-02,  3.4144e-02,  3.7860e-02,  4.4344e-03,  1.7261e-02,
         3.5435e-02,  4.9303e-03, -6.5806e-02,  5.3186e-02, -2.2003e-02,
        -1.9945e-02, -5.4883e-02, -2.1081e-02,  2.4584e-02, -4.4336e-03,
         6.0846e-02,  2.3314e-02,  2.7127e-02, -5.9566e-02,  2.9488e-02,
        -2.0912e-02, -1.3108e-02, -5.7090e-02, -1.5656e-02, -5.5888e-02,
         4.3393e-02,  7.6781e-02, -1.1601e-02, -7.9059e-03, -4.6870e-02,
         2.6403e-02,  1.0498e-03,  2.3262e-02,  6.6447e-02, -1.8533e-02,
         8.6163e-03, -2.9885e-02,  2.4040e-04, -2.6038e-02, -3.6502e-03,
        -6.6727e-02, -3.2013e-03, -4.4877e-02, -7.0054e-02, -3.7473e-02,
         2.9750e-02,  1.1229e-02, -9.4330e-02, -5.4170e-02,  4.6131e-02,
         2.8569e-02,  1.0029e-02,  1.7027e-02, -6.1399e-02,  3.9956e-03,
         5.0130e-02,  4.6296e-02, -4.3378e-02, -7.4134e-03,  1.8500e-02,
        -4.3106e-02,  4.9759e-03,  4.8757e-02, -1.3205e-02,  8.0337e-02,
        -5.5325e-03,  7.7579e-02,  8.9057e-03, -1.9425e-02, -3.4517e-02,
         2.1837e-02, -5.5787e-02, -4.5653e-02, -4.7375e-02,  4.5612e-02,
         1.5212e-02,  1.2009e-02, -2.8737e-02, -2.2183e-02, -9.0711e-03,
        -3.3577e-03,  3.4510e-02,  2.9412e-02, -6.2508e-02,  8.4548e-03,
        -2.4942e-03, -3.5745e-03,  3.0905e-02,  1.2730e-02, -1.7714e-02,
        -7.4126e-03,  4.4466e-02,  4.1551e-03, -3.0779e-02, -3.5871e-02,
         2.7599e-03,  3.5902e-02,  2.2108e-02,  3.5839e-02, -3.0451e-02,
         2.0057e-02,  5.9347e-02, -1.5905e-02, -1.5088e-02,  8.8894e-03,
        -3.2719e-02, -4.0633e-03,  3.0831e-02,  4.0040e-02, -2.0248e-02,
        -1.4036e-02, -5.4754e-03,  7.1753e-03,  1.1974e-01, -3.6252e-02,
         6.4244e-02,  2.2986e-02, -6.3504e-03, -1.6589e-02, -2.5306e-02,
         2.7004e-02,  1.4398e-02, -4.7315e-02,  2.2142e-02, -3.1512e-02,
        -2.5302e-02,  1.8080e-02, -4.5988e-02,  2.6482e-02, -8.7065e-03,
         9.7601e-02,  7.7628e-03, -2.5615e-02,  7.0686e-02,  3.3959e-02,
         6.2573e-03, -1.8817e-03, -3.4409e-02, -1.6801e-02, -2.7810e-02,
         2.4625e-03, -4.5146e-03,  5.6373e-02,  1.2260e-02, -3.4159e-02,
         5.2329e-03, -1.1383e-02, -2.3258e-02, -1.4594e-02, -1.4920e-02,
        -4.3798e-03, -3.3721e-03,  4.1109e-02, -1.0796e-01,  7.1829e-03,
        -2.3833e-02,  3.6013e-02, -4.6286e-03, -1.9363e-02,  4.8809e-02,
         1.5642e-02, -1.1102e-02, -1.6208e-02, -2.4455e-03, -1.0532e-02,
        -2.4673e-02, -2.4320e-02, -1.4617e-02,  4.4378e-02,  4.4309e-02,
         5.2636e-02, -2.7875e-02,  1.2963e-02,  1.7866e-03,  1.5689e-02,
        -1.5433e-02, -4.1849e-02,  2.5260e-02,  4.5207e-02,  2.4650e-02,
         3.1631e-02,  7.1006e-03,  1.1461e-02, -4.7826e-02, -3.6058e-02,
         3.7481e-02,  1.4131e-02, -7.2017e-02, -2.3894e-03,  6.6905e-02,
        -3.0184e-03, -1.0535e-02,  2.3501e-02, -4.1193e-02, -2.3653e-02,
         1.6378e-02,  1.3552e-02, -3.5403e-02, -1.2376e-02, -1.8760e-02,
         3.9180e-02,  1.4428e-02,  2.4904e-02, -1.7295e-01, -9.8387e-04,
         2.5280e-02,  2.1064e-02,  4.0104e-02, -1.0587e-02,  2.3535e-02,
         6.6978e-03, -2.7715e-02, -2.7532e-02,  7.4456e-02, -4.0099e-02,
        -1.3613e-02, -6.9905e-02, -9.3003e-02,  7.0099e-02,  1.0740e-02,
        -2.8206e-02, -7.3355e-03,  1.8342e-02, -1.2556e-02, -2.7323e-03,
         4.1015e-02, -8.8775e-02, -1.8340e-02, -3.9479e-02,  3.9275e-02,
        -8.1136e-03,  2.2492e-02, -2.5726e-02,  4.1877e-02,  4.6411e-02,
         5.1925e-02, -6.0102e-02, -2.6657e-03, -2.1908e-02,  6.0480e-02,
         1.3035e-03,  1.2975e-02, -3.6995e-02,  4.4567e-02, -2.8876e-02,
        -5.4305e-02, -7.0865e-02, -1.3641e-02, -3.7260e-04, -7.3201e-02,
        -4.6192e-03,  2.3844e-02,  2.7764e-02, -2.6731e-02,  1.7593e-02,
        -4.0601e-03, -2.0794e-02,  7.0033e-03, -7.8716e-03, -1.0443e-01,
         4.5298e-03,  5.1152e-02, -8.0720e-02, -4.4315e-03,  6.1582e-03,
         1.9896e-02,  3.9291e-02, -9.6105e-04, -2.5500e-02, -3.4748e-02,
         7.0318e-03, -2.6919e-02, -1.6950e-02,  3.9061e-02,  3.9689e-02,
        -1.1507e-02,  3.0816e-02, -4.6172e-02,  6.2569e-02, -4.7334e-02,
         1.7538e-02, -2.9626e-02, -3.2612e-02,  6.2265e-02, -4.6661e-02,
        -5.3758e-04, -3.6305e-02, -3.0520e-02, -3.0109e-02, -6.2540e-02,
         8.9415e-03,  2.9186e-02, -4.4351e-02, -2.7682e-02,  5.1570e-03,
        -5.1732e-03, -3.1927e-03,  1.0116e-02, -9.2100e-03,  4.4626e-02,
        -2.2088e-02,  1.6127e-02,  3.2246e-02,  4.6533e-02,  7.5450e-02,
         2.5181e-02, -5.2918e-03,  2.7647e-02,  4.5635e-02, -1.5615e-02,
        -2.9128e-02,  3.0052e-02, -9.2364e-03, -8.9962e-04,  5.4961e-02,
         6.3365e-02,  6.1146e-02,  9.8382e-03, -2.6866e-02,  3.4254e-03,
         5.5133e-02,  2.5554e-02, -7.4605e-03,  4.1119e-02, -2.7938e-02,
         3.8135e-02, -2.0449e-02, -2.7410e-02, -1.7101e-02, -7.0768e-03,
         1.4303e-02, -1.5528e-02, -1.1215e-02, -6.9734e-03,  4.3606e-03,
        -1.9205e-02, -1.3459e-02,  2.0092e-02,  4.6003e-02, -8.3712e-02,
        -6.1560e-02, -7.8821e-03,  9.9551e-03, -1.5194e-02, -7.0649e-03,
         1.6719e-02, -5.3590e-02, -2.0692e-02,  4.0972e-02,  3.6766e-02,
        -1.3369e-02,  9.1570e-03,  1.5016e-02, -6.1266e-02,  3.5633e-02,
         6.2994e-03, -1.3616e-02, -3.0314e-03,  2.3011e-02, -1.1966e-03,
         4.8466e-02, -7.0087e-02,  1.2271e-01, -3.8029e-02,  2.8110e-02,
         6.1267e-03, -2.7783e-03, -1.0654e-02,  1.1184e-02,  4.8569e-02,
         5.7653e-02, -6.1529e-02, -6.4028e-02,  6.4392e-03, -4.0543e-02,
        -2.6113e-02, -1.0014e-02, -5.4635e-02,  4.3596e-04,  6.8349e-02,
        -6.0644e-33,  7.5755e-02, -3.0567e-02,  3.2421e-02,  8.2907e-02,
         3.0398e-02,  3.9693e-02,  2.2608e-02, -3.9555e-02, -3.8684e-02,
        -1.3910e-02,  5.1663e-02,  3.7058e-02, -1.0291e-02, -1.1874e-02,
         4.7205e-02, -7.4189e-03, -2.1283e-03, -3.1514e-02, -2.4717e-02,
        -1.0815e-02, -1.2765e-02, -8.2311e-03,  4.2798e-02, -1.1078e-02,
         7.1328e-03,  8.4981e-03,  1.2830e-03,  1.3901e-03, -5.4441e-02,
         3.1034e-02, -3.1801e-02,  7.4809e-02,  1.9685e-02, -9.0973e-03,
        -2.4451e-02, -3.9677e-03, -6.1823e-02, -2.4951e-02,  4.7066e-02,
        -3.0215e-03, -8.2348e-02, -1.9701e-02, -2.4493e-02, -8.1855e-03,
         1.9200e-03, -1.0817e-02, -3.7590e-02, -1.5628e-02,  6.0136e-02,
         5.8943e-03,  5.3091e-02,  1.4165e-02,  1.0813e-03,  1.6126e-02,
        -4.3493e-03,  9.3918e-02, -1.5926e-02, -1.1046e-02,  7.7050e-02,
         2.3553e-02, -1.8821e-04,  4.7702e-02, -2.1051e-02,  5.6182e-02,
         1.1741e-02, -2.7484e-03, -4.0515e-02,  6.2439e-04, -4.3655e-02,
         3.6976e-03,  1.4233e-02, -1.1873e-02, -6.2708e-03,  5.3183e-03,
        -1.8054e-02,  6.1363e-03, -1.0901e-02,  2.6975e-02, -2.9714e-02,
        -2.8171e-02, -4.6066e-02, -2.3119e-02,  2.8594e-02, -1.4409e-02,
         2.3553e-02, -1.8274e-02, -1.0684e-04,  8.1575e-04,  4.3281e-04,
        -5.9529e-03, -2.9617e-02,  4.9436e-02,  9.3778e-03, -2.3388e-02,
         2.6592e-02,  1.3257e-02,  1.5067e-02, -5.1231e-02,  3.1505e-03,
        -3.0002e-02, -5.3071e-02,  1.0417e-02,  2.6223e-02, -1.0552e-02,
        -2.0650e-02, -1.2315e-02, -5.3509e-02,  6.1850e-03,  6.1221e-02,
        -7.0266e-02,  1.7831e-02, -6.9401e-03,  4.3127e-02, -1.2616e-02,
        -2.6923e-02, -9.6886e-05,  1.1358e-02,  4.6819e-02, -3.1469e-02,
         4.3581e-03, -2.2380e-02,  5.4560e-02,  2.0144e-02, -5.2396e-02,
         1.7421e-02, -6.4686e-02,  3.7406e-02,  1.6154e-02,  2.9067e-02,
         4.7817e-02,  2.8745e-03,  3.7516e-02,  3.1023e-07,  4.0240e-02,
        -2.5076e-05, -6.8407e-03, -1.0164e-01, -2.6103e-02, -2.8820e-02,
         3.6350e-02, -1.9227e-02, -5.8941e-02,  3.8505e-02,  6.3905e-02,
        -6.4702e-02,  1.3853e-03,  1.5382e-02, -6.9400e-03, -3.8877e-03,
        -1.8114e-02, -7.4352e-02,  2.7403e-02, -2.7637e-02, -5.9266e-03,
        -1.9828e-02, -5.5644e-02,  1.4025e-02, -3.7951e-02, -7.8981e-04,
         1.0449e-02, -2.6430e-02,  3.3703e-02,  1.5062e-02,  4.2838e-02,
         1.5763e-02,  9.7988e-03,  1.5375e-02, -3.3320e-02,  5.9000e-03,
         9.4854e-03, -4.7308e-03, -1.1861e-02,  7.6481e-03, -5.5295e-02,
         2.2890e-02,  2.5381e-02,  5.8303e-03, -4.1173e-02, -8.1986e-02,
        -1.8529e-02, -5.9256e-03,  2.0056e-02,  1.5571e-02, -3.3635e-02,
         4.2398e-03, -2.6668e-02, -7.9585e-03, -2.8255e-02,  6.7718e-03,
         3.5839e-02,  1.2693e-02,  1.4607e-02,  5.7228e-02, -5.8674e-03,
        -2.2222e-02, -3.5415e-03, -3.9669e-02,  2.3686e-02,  2.0786e-02,
        -9.2950e-03,  2.4216e-34, -1.4754e-02, -2.1534e-02,  7.0148e-03,
        -2.7719e-02, -2.8251e-02,  1.4644e-02, -8.5230e-02,  1.3003e-02,
        -1.5546e-02, -2.3844e-02, -7.3636e-04], device='cuda:0')

# Save text and embeddings to csv file.

In [31]:
text_chunks_and_embeddings_df = pd.DataFrame(filtered_chunks)
text_chunks_and_embeddings_df.to_csv("text_chunks_and_embeddings_df.csv",index=False)

In [32]:
#Import the csv file and see data
text_chunk_and_embeddings_load = pd.read_csv("text_chunks_and_embeddings_df.csv")
text_chunk_and_embeddings_load.head()

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,chunk_embedding
0,-16,Human Nutrition Copyright © 2022 by Melissa Jo...,238,30,59.50,[ 3.88624743e-02 5.59770241e-02 -5.76988840e-...
1,-15,CONTENTS Preface xiii About the Contributors x...,518,79,129.50,[ 4.28345352e-02 4.43807244e-02 5.18328277e-...
2,-14,The Endocrine System 85 The Urinary System 89 ...,767,123,191.75,[ 5.54008633e-02 4.40658145e-02 1.09777590e-...
3,-13,Part V. Protein Introduction 219 Defining Prot...,646,93,161.50,[ 5.20048738e-02 1.00022936e-02 5.58838341e-...
4,-12,Part VIII. Water and Electrolytes Introduction...,559,80,139.75,[ 4.85534072e-02 -1.86877344e-02 -3.01864967e-...

# Similarity Search

-Similarity search or semantic search or vector search is the idea of searching on *vibe*.

If this sounds like woo, woo. It's not.

Perhaps searching via *meaning* is a better analogy.

With keyword search, you are trying to match the string "apple" with the string "apple".

Whereas with similarity/semantic search, you may want to search "macronutrients functions".

And get back results that don't necessarily contain the words "macronutrients functions" but get back pieces of text that match that meaning.

> **Example:** Using similarity search on our textbook data with the query "macronutrients function" returns a paragraph that starts with:
>
>*There are three classes of macronutrients: carbohydrates, lipids, and proteins. These can be metabolically processed into cellular energy. The energy from macronutrients comes from their chemical bonds. This chemical energy is converted into cellular energy that is then utilized to perform work, allowing our bodies to conduct their basic functions.*

In [33]:
import random

import torch
import numpy as np
import pandas as pd

device = "cuda" if torch.cuda.is_available() else "cpu"

#import text and embedding df
text_chunks_and_embeddings_df = pd.read_csv("text_chunks_and_embeddings_df.csv")

#convert embeddings column back to np array(it got converted to string when it got saved to csv)
text_chunks_and_embeddings_df["chunk_embedding"] = text_chunks_and_embeddings_df["chunk_embedding"].apply(lambda x: np.fromstring(x.strip("[]"), sep=" "))

#convert embeddings to torch tensor and send to the device(note: Numpy arrays are float64, torch tensors are float32 by default)
embeddings = torch.tensor(np.array(text_chunks_and_embeddings_df["chunk_embedding"].tolist()), dtype=torch.float32).to(device)

embeddings.shape

torch.Size([1571, 768])

now we have small data like 1571 chunking so we donot need to batch.Also we only search similarity not train model.So donot need batching.

For RAG simple pipeline<br>
1.Define a query<br>
2.Embeddings of query(Note: must use same embedding model to embed the query which we embed the sentence chunk)<br>
3.Perform a dot product or cosine similarity function over a query embeddings and text embeddings.<br>
4.Sort the result from desending order using top- k.

In [99]:
#define a query
import torch
import torch.nn.functional as F

query = "What are Macronutrients and What are thier roles?"
print(f"query:{query}")

#Embeddings of query
query_embedings = model.encode(query,convert_to_tensor=True).to(device)

#dot product of query and text embeddings
similarity = F.cosine_similarity(embeddings,query_embedings)

#Get the top k results
top_result_similarity = torch.topk(similarity,k=3)

top_result_similarity

query:What are Macronutrients and What are thier roles?

torch.return_types.topk(
values=tensor([0.7079, 0.6692, 0.6572], device='cuda:0'),
indices=tensor([21, 27, 26], device='cuda:0'))

In [100]:
filtered_chunks[21]

{'page_number': 5,
 'sentence_chunk': 'Macronutrients Nutrients that are needed in large amounts are called macronutrients. There are three classes of macronutrients: carbohydrates, lipids, and proteins. Through various biological processes occurring in the body, these nutrients can be metabolized to produce cellular energy. The energy from macronutrients comes from their chemical bonds. This chemical energy is converted into cellular energy that is then utilized to perform work, allowing our bodies to conduct their basic functions. The energy obtained from food, which thus becomes cellular energy, is measured in calorie units. A unit of measurement of food energy is the calorie. On nutrition food labels, the amount given for “calories” is actually equivalent to each calorie multiplied by one thousand. A kilocalorie (one thousand calories, denoted with a small “c”) is synonymous with the “Calorie” (with a capital “C”) on nutrition food labels. Although water does not yield calories, it is considered to be a macronutrient because it is needed in large amounts daily.',
 'chunk_char_count': 1042,
 'chunk_word_count': 158,
 'chunk_token_count': 260.5,
 'chunk_embedding': array([ 4.26693261e-02, -5.60707487e-02,  1.94342490e-02,  1.72816515e-02,
         4.57053483e-02,  1.51731074e-02, -7.83894733e-02,  1.94945801e-02,
        -2.53333356e-02, -3.15270536e-02,  3.27522568e-02,  1.89718362e-02,
         2.07598601e-02,  2.18953807e-02,  3.26371156e-02, -2.23143417e-02,
         6.07693531e-02, -4.38207611e-02, -4.13420461e-02,  3.84948254e-02,
         6.87847659e-03,  1.29719758e-02,  3.38058621e-02, -7.57903326e-03,
        -1.04580306e-01,  4.61822487e-02,  3.44308950e-02,  8.65465775e-03,
         1.75236535e-04, -5.73655702e-02, -1.31505802e-02, -8.02474190e-03,
        -4.66985442e-02, -3.21020707e-02,  2.10813414e-06, -4.11915407e-02,
        -3.22921053e-02,  1.66696198e-02, -6.92016184e-02,  1.95993036e-02,
         1.59166331e-04, -5.06073460e-02,  2.19884105e-02, -1.46515165e-02,
         4.66991402e-02,  4.11378294e-02,  4.45010886e-02, -3.16675976e-02,
        -4.72742803e-02, -1.13604842e-02,  5.22839697e-03, -4.77141555e-04,
         1.11655360e-02, -1.03070168e-02,  2.59649549e-02,  3.57610807e-02,
         2.07561199e-02,  6.69587106e-02, -2.05298997e-02,  5.00110388e-02,
         3.77118737e-02,  2.98941284e-02,  8.45661666e-03, -1.04340799e-02,
         4.90584821e-02,  6.38078079e-02, -4.59673218e-02, -2.47126427e-02,
         3.74650874e-04,  5.09322360e-02, -1.79377161e-02,  1.27002615e-02,
         1.96786076e-02, -6.99760334e-04, -1.90352146e-02, -4.75197705e-03,
         4.04090844e-02, -2.86167245e-02,  4.31656316e-02,  7.24575808e-03,
        -8.55854247e-03,  2.32653525e-02,  2.78875306e-02, -5.86286886e-03,
        -1.85495391e-02, -5.04801907e-02, -3.22785787e-02,  5.14462171e-03,
        -3.49672930e-03, -4.16535065e-02, -8.46190378e-02, -3.19093913e-02,
         5.50559424e-02,  9.45646036e-03,  9.13350955e-02, -1.48168281e-02,
        -1.20994765e-02,  5.85616939e-02,  8.01929682e-02, -4.68246192e-02,
        -2.51805875e-02, -2.15190500e-02,  1.02488662e-03,  1.49030155e-02,
         2.73140526e-04,  1.93367768e-02,  1.76490715e-03, -4.73345630e-02,
        -4.58012931e-02,  1.12548685e-02, -4.34772037e-02, -2.69106682e-02,
        -3.90035026e-02,  3.20011154e-02, -3.16852815e-02,  5.17249741e-02,
        -3.68046612e-02, -1.36766746e-03, -3.59476469e-02,  1.20762922e-02,
        -8.97566881e-03,  2.76331790e-02,  2.87029482e-02, -1.00023700e-02,
        -2.32581515e-02,  7.49199167e-02,  1.62436739e-02, -5.09148613e-02,
         8.54226388e-03, -6.66132346e-02,  7.67484074e-03, -8.78572930e-03,
        -2.71197855e-02,  1.72154550e-02, -1.55330505e-02,  2.33183932e-02,
         3.25408205e-02, -1.11987097e-02,  2.36567706e-02, -8.32831860e-02,
        -1.08897321e-01, -3.42019424e-02, -5.94963953e-02,  6.47299970e-03,
         1.19049484e-02,  3.52895586e-03,  4.93859053e-02,  4.77018207e-02,
         5.57802133e-02,  6.72035618e-03,  9.13147721e-03,  4.05401699e-02,
         3.71073894e-02,  2.09134370e-02,  5.09267524e-02, -3.01623102e-02,
         3.29449363e-02, -3.79063077e-02,  7.87581056e-02,  9.60079953e-03,
         9.09099262e-03, -1.83473490e-02, -3.22542936e-02, -1.66171510e-02,
        -2.13900935e-02, -3.50316875e-02,  7.45534105e-03, -9.53967776e-03,
         8.92194826e-03,  8.02591629e-03, -1.05431313e-02, -1.73114445e-02,
        -1.68235954e-02,  3.63702960e-02,  4.93735410e-02,  1.06795812e-02,
        -7.06342934e-03,  1.73478369e-02, -4.56685387e-02,  7.95244053e-03,
         2.31035687e-02, -2.44419519e-02,  1.15391202e-02,  3.95978615e-02,
        -6.79369867e-02, -4.04483192e-02,  1.04464972e-02, -6.36601895e-02,
         1.24491397e-02, -1.81238689e-02,  5.43932095e-02, -1.99945550e-02,
        -1.43567463e-02, -6.04314543e-02,  2.97464933e-02, -5.92675002e-04,
        -6.31168485e-03,  1.49114449e-02, -8.04266613e-03, -2.39940844e-02,
         3.38255316e-02,  8.37994143e-02, -2.66541131e-02,  6.16120966e-03,
        -7.88887143e-02,  2.51422245e-02,  3.75174098e-02,  1.29561601e-02,
         9.38275829e-03, -1.09847868e-02, -8.08470231e-03, -4.71675172e-02,
         1.27515988e-03, -4.23764903e-03, -7.02322880e-03, -7.28583261e-02,
        -1.17836911e-02, -2.17710510e-02, -6.45178556e-02,  3.12027242e-02,
         2.90999375e-02, -3.26623656e-02, -7.38283098e-02, -5.24811149e-02,
         8.60617310e-02, -6.03377707e-02,  7.61323050e-03, -1.36315785e-02,
        -8.86110440e-02,  2.14242190e-02,  4.70837988e-02,  5.41351587e-02,
        -2.39939541e-02, -7.95209035e-03, -3.89851145e-02, -2.50449758e-02,
        -1.23340068e-02,  4.22998630e-02, -1.25074536e-02,  4.48845066e-02,
        -2.47517060e-02, -2.73253676e-02,  1.81574747e-02,  9.76744853e-03,
        -6.09231405e-02,  2.20653266e-02, -4.27863821e-02, -2.14351658e-02,
        -1.28421057e-02,  4.88665476e-02,  2.11688280e-02,  2.53673457e-03,
         8.73006321e-03, -1.36957467e-02,  1.27862524e-02, -1.96228526e-03,
         6.87905997e-02, -1.95280481e-02,  2.14065239e-03,  3.27134021e-02,
         7.06022680e-02,  5.14559262e-03,  2.58947015e-02,  2.91908942e-02,
        -4.35295403e-02, -3.64563167e-02, -1.00228637e-02,  5.63155711e-02,
         1.33064976e-02, -1.41759766e-02,  2.42477935e-02,  2.90987398e-02,
         2.04768195e-03,  5.80937788e-02,  1.07176472e-02,  8.19531363e-03,
         1.63412355e-02, -2.72957645e-02,  2.12584045e-02, -1.26025612e-02,
        -1.50459409e-02,  5.30784167e-02,  2.39342712e-02,  1.72214508e-02,
        -9.01615061e-03,  2.90425997e-02,  1.50187798e-02,  3.03498227e-02,
         7.82354474e-02, -1.01269279e-02,  6.18725978e-02, -3.24926786e-02,
        -8.07551842e-04, -4.93624434e-03, -6.43827859e-03,  8.46560113e-03,
         3.02088689e-02, -4.73319627e-02,  4.93434742e-02,  2.12821271e-02,
         4.37183306e-03, -1.36516793e-02, -7.45717511e-02,  1.02763018e-02,
        -1.55836707e-02,  1.30212661e-02,  1.25059057e-02, -3.47268470e-02,
         5.56537434e-02,  4.21974808e-02,  8.93770996e-03,  5.11847064e-02,
        -7.16164708e-03,  5.22121303e-02, -5.11289909e-02,  1.06544737e-02,
        -3.89145389e-02,  7.39834532e-02,  3.36224586e-02, -3.95884588e-02,
         4.29210346e-03, -7.67153455e-03, -2.14646887e-02, -9.54392180e-03,
        -2.77528949e-02,  6.23290660e-04, -1.81637276e-02,  8.46366584e-02,
        -8.40290561e-02,  1.21971248e-02, -2.76615787e-02,  1.82530340e-02,
         2.57044975e-02,  2.78650448e-02,  3.67064811e-02,  1.63963512e-02,
        -3.54625583e-02, -2.85572335e-02,  3.96331213e-03, -1.58727095e-02,
        -3.07055153e-02, -1.78675316e-02, -5.04396716e-03,  7.57092014e-02,
         3.58058363e-02,  7.12775737e-02,  2.97298972e-02, -6.69956626e-03,
         1.42710311e-02,  2.89746542e-02,  8.61864723e-03, -5.91608882e-03,
        -1.21303964e-02, -6.55596284e-03, -1.96344163e-02,  7.05194697e-02,
        -1.96144078e-03, -2.12645251e-02, -3.54480334e-02, -5.22049591e-02,
         6.59178942e-02,  8.23902413e-02, -6.64092228e-02, -5.06793559e-02,
         2.71771103e-02,  9.40982439e-03, -3.12271453e-02,  1.17301624e-02,
         2.26954967e-02, -2.27875635e-02,  2.78357994e-02, -1.45328231e-02,
        -5.40209096e-03, -4.94890555e-04,  1.78261213e-02,  6.88715512e-03,
         2.91178431e-02,  3.34947705e-02, -1.15975671e-01,  1.57762654e-02,
         8.63030739e-03,  2.67302748e-02,  3.61102335e-02, -9.60427709e-03,
         2.30258703e-03,  6.29627437e-04, -2.36978289e-02, -2.94853523e-02,
         6.19056970e-02, -6.52762353e-02,  2.46695466e-02, -4.26144116e-02,
        -6.54595718e-02,  3.43418904e-02,  3.19653377e-03,  1.69936027e-02,
        -1.48398522e-02,  1.15916179e-02, -1.83514860e-02,  3.47515009e-02,
         3.95100079e-02, -1.68132689e-02,  5.93430772e-02, -5.27961645e-03,
        -4.69982112e-03,  4.17678431e-02,  5.78384995e-02, -2.99383700e-03,
        -2.41025770e-03,  4.23857309e-02, -7.80608854e-04, -5.59830107e-02,
        -3.73071954e-02, -2.27917805e-02,  1.87653564e-02,  2.79844720e-02,
        -1.82627479e-03,  2.67452793e-03,  2.86268499e-02, -2.34544855e-02,
        -4.50225659e-02, -9.16587189e-03,  1.64046958e-02,  1.96195431e-02,
        -8.04258510e-02,  1.47164911e-02, -2.33358648e-02,  2.20205169e-02,
        -2.61568632e-02,  3.63637172e-02,  1.08619202e-02, -5.73435314e-02,
        -1.51618375e-02, -1.03392703e-02, -6.29123151e-02,  5.46511337e-02,
         6.24224395e-02, -7.94776827e-02, -6.42441073e-03,  9.23314225e-03,
        -6.43313304e-03,  1.66844707e-02,  7.22657377e-03, -5.77907718e-04,
         1.18022342e-03,  5.79647571e-02, -2.69203503e-02, -1.94323398e-02,
         7.08448440e-02,  1.48616098e-02,  2.06300654e-02,  3.43561284e-02,
        -6.66512102e-02,  8.90337825e-02,  2.04129480e-02,  4.14239755e-03,
        -3.79988961e-02, -6.23190450e-03, -6.19153539e-03, -9.28794369e-02,
         1.95210688e-02, -1.82943884e-02, -2.09852718e-02,  7.02607853e-04,
        -4.53888848e-02, -1.29132941e-02,  5.37879840e-02, -6.08342327e-02,
        -1.60019509e-02, -2.35139579e-02, -4.84272232e-03,  2.55467575e-02,
         1.16774684e-03, -1.34031046e-02,  3.74178328e-02, -6.74230680e-02,
         2.52991589e-03, -3.27366553e-02, -1.23228841e-02,  5.78113832e-02,
        -7.83595815e-03, -1.23338383e-02,  3.48571241e-02,  9.76900198e-03,
        -5.88138646e-04, -3.28314155e-02,  1.60806831e-02, -3.31646167e-02,
        -1.36102187e-02, -6.13568351e-02,  2.32523084e-02,  8.01141858e-02,
        -2.98404191e-02, -4.83611785e-02,  6.46854751e-03, -1.45985475e-02,
         2.19686385e-02, -1.63693633e-02,  4.49049883e-02,  3.92409377e-02,
         3.92143987e-02, -2.06948239e-02,  3.57971364e-03, -2.15270557e-02,
         5.34542277e-03,  2.09065173e-02, -2.62566414e-02, -3.88417616e-02,
         8.38752650e-03,  1.69135362e-03, -2.37006471e-02,  2.98445523e-02,
         1.21451933e-02,  6.78301826e-02, -2.55272072e-02, -9.10486132e-02,
        -2.27491409e-02,  9.73544433e-04, -1.40816076e-02, -2.52573751e-02,
         2.60305889e-02, -4.78122495e-02,  2.45306850e-03, -2.14919820e-02,
         1.72736440e-02,  5.36143929e-02,  8.08068831e-03,  5.48860990e-03,
        -4.42707129e-02,  4.36553471e-02,  2.61302050e-02, -1.39438743e-02,
        -2.38238554e-02, -5.27203195e-02,  2.93145776e-02,  5.85192889e-02,
        -1.01761766e-01,  8.42420413e-05, -3.18162292e-02,  1.48561094e-02,
        -4.18114616e-03, -1.83420479e-02,  1.93408784e-02,  2.42696144e-02,
         5.72306514e-02,  2.68332511e-02, -3.82567793e-02, -5.01818620e-02,
         6.50423067e-03, -8.98436829e-02, -7.22102867e-03,  6.49921000e-02,
        -6.24674559e-03, -2.18670256e-02,  6.57723546e-02, -5.99088161e-33,
         2.43392959e-02, -9.75212157e-02,  6.52831094e-03,  8.81641954e-02,
        -1.90306865e-02,  7.20829815e-02, -1.68786161e-02,  3.30630294e-03,
        -2.00179890e-02,  1.15200868e-02,  2.94662230e-02,  1.45723848e-02,
         1.89668518e-02, -3.09738368e-02,  3.79857011e-02, -3.22344862e-02,
         3.71476673e-02, -4.93421406e-02, -5.65574644e-03, -8.02235561e-04,
        -1.39760133e-02, -4.91210483e-02,  3.03712580e-02, -1.25715015e-02,
         5.05387336e-02,  9.90434084e-04,  8.66993517e-03, -3.12557700e-03,
        -3.24974023e-03,  3.45364995e-02,  7.15859060e-04,  7.23883137e-02,
         3.10963728e-02,  1.77469272e-02, -8.32433719e-03,  1.55704757e-02,
        -2.38924306e-02, -2.93761529e-02, -1.96701586e-02,  4.22262028e-02,
        -7.91150331e-02, -4.02829796e-02, -3.96288447e-02, -1.24106379e-02,
        -5.25644124e-02,  4.45843041e-02, -2.83170175e-02,  9.22992453e-03,
        -4.29670792e-03,  9.56940558e-03,  3.67187485e-02,  1.98052507e-02,
        -2.54018921e-02,  5.10342978e-02,  3.86935845e-03,  1.44984685e-02,
        -7.55811622e-03, -1.95314065e-02,  1.59885772e-02,  4.42885188e-03,
         4.48071733e-02,  6.42807186e-02, -1.01046227e-02,  6.39021248e-02,
        -1.74993966e-02, -1.10889394e-02,  2.09573787e-02,  3.14761586e-02,
        -4.52607907e-02, -4.64339321e-03, -2.18405109e-02,  6.72149332e-03,
         2.86727399e-03, -5.23893815e-03,  1.27141438e-02, -5.16862907e-02,
        -1.41693866e-02,  2.83350404e-02, -4.38763201e-02, -6.35612831e-02,
        -4.80750464e-02, -3.45664471e-02,  3.69244441e-02, -3.51109952e-02,
        -1.87569428e-02, -6.64131623e-03, -5.69983432e-03,  1.35434400e-02,
         2.11249553e-02, -6.35849312e-02,  5.58256230e-04, -1.66315981e-03,
         1.06675746e-02, -6.41589100e-03,  4.80490848e-02, -1.41407885e-02,
         4.65905331e-02, -5.08848112e-03, -2.56275013e-02,  2.96171680e-02,
        -4.24279049e-02,  1.68059394e-02, -2.81914021e-03, -6.66654110e-02,
        -1.07021015e-02, -1.70961618e-02, -7.47683570e-02, -1.82554213e-04,
         5.50315082e-02, -3.53745520e-02,  3.71614681e-03, -2.97785271e-02,
         4.55016457e-03, -7.81605467e-02, -3.19398530e-02,  3.02493805e-03,
         3.05826738e-02,  1.48285087e-02,  1.33976014e-02, -4.00463641e-02,
        -3.33137959e-02, -1.08608222e-02,  3.35153490e-02, -8.45200568e-03,
        -4.24496969e-03, -2.66109444e-02, -9.24393907e-03, -3.25170765e-03,
         2.13677343e-02,  3.88941802e-02,  1.17163630e-02,  4.56959009e-02,
         2.88879704e-07,  2.68564257e-03, -1.66388764e-03,  8.45983159e-04,
        -7.54152685e-02, -3.79406381e-03,  7.97215663e-03,  3.35530564e-02,
        -2.73328070e-02, -3.98467332e-02, -4.70265793e-03,  1.96344461e-02,
        -7.92894140e-02,  5.58240665e-03,  2.22688857e-02,  8.65762830e-02,
         1.61253475e-02,  4.39860001e-02, -4.91905026e-02,  2.22168062e-02,
        -2.82172281e-02, -4.31990027e-02, -6.06758259e-02, -6.08964935e-02,
        -2.17743614e-03, -6.86678290e-02, -3.04414369e-02,  2.73197517e-02,
        -2.90146060e-02,  7.76415318e-02,  1.31929908e-02,  2.84611117e-02,
        -5.17851627e-03,  3.45868282e-02,  2.01192964e-02, -1.92184094e-02,
         2.31617945e-03,  2.70825569e-02,  3.83109935e-02, -9.14539490e-03,
         2.04249956e-02, -3.76108661e-02, -9.54091921e-03, -1.47260418e-02,
        -5.12978015e-03, -3.64301279e-02, -3.30128521e-02,  1.35235779e-03,
        -1.42564792e-02,  3.91557813e-02, -1.45621402e-02, -5.92204183e-02,
         3.32181789e-02, -2.95126159e-02,  2.97607053e-02,  2.47911830e-03,
         2.95792483e-02,  1.16663016e-02,  5.90579286e-02,  5.16085550e-02,
        -3.76805011e-03, -1.12134079e-02,  9.40802693e-03, -4.39454615e-03,
         4.03903099e-03,  4.09025364e-02,  9.37711596e-02,  4.14300757e-03,
         2.13325524e-34, -1.61128752e-02, -3.79543416e-02, -3.02151544e-03,
        -1.50594944e-02, -5.16131744e-02,  3.14565450e-02, -9.75634083e-02,
        -1.01342087e-03,  7.73357274e-03, -5.24264351e-02, -3.07926740e-02],
       dtype=float32)}

Use vector db and FAISS and ANN(Nearest Neighbor) for the big data more than 1M to calculate similarity.

Now make our vector ouput more pretty.

In [101]:
import textwrap
def print_wrapped(text,wrap_length=80):
  wrapped_text = textwrap.fill(text,wrap_length)
  print(wrapped_text)

# this func do Text automatically broken into multiple lines
#Each line ≤ 50 characters
#Makes text readable in console / terminal

In [102]:
query = "What are Macronutrients and what roles they play?"
print(f"query:{query}\n")
print("Result:")

#Loop through zip together scores and indices from torch.topk
#top k garda indices,values ma aauxa so hamle top_result_similarity[0] and 1 use gareko for values and indices.
for score,idx in zip(top_result_similarity[0],top_result_similarity[1]):
  print(f"Score:{score:.4f}")
  print("Text:")
  print_wrapped(filtered_chunks[idx]["sentence_chunk"])
  print(f"Page Number:{filtered_chunks[idx]["page_number"]}")
  print("\n")

query:What are Macronutrients and what roles they play?

Result:
Score:0.7079
Text:
Macronutrients Nutrients that are needed in large amounts are called
macronutrients. There are three classes of macronutrients: carbohydrates,
lipids, and proteins. Through various biological processes occurring in the
body, these nutrients can be metabolized to produce cellular energy. The energy
from macronutrients comes from their chemical bonds. This chemical energy is
converted into cellular energy that is then utilized to perform work, allowing
our bodies to conduct their basic functions. The energy obtained from food,
which thus becomes cellular energy, is measured in calorie units. A unit of
measurement of food energy is the calorie. On nutrition food labels, the amount
given for “calories” is actually equivalent to each calorie multiplied by one
thousand. A kilocalorie (one thousand calories, denoted with a small “c”) is
synonymous with the “Calorie” (with a capital “C”) on nutrition food labels.
Although water does not yield calories, it is considered to be a macronutrient
because it is needed in large amounts daily.
Page Number:5


Score:0.6692
Text:
micronutrients are not sources of energy (calories), but they assist in the
process as cofactors or components of enzymes (i.e., coenzymes). Enzymes are
proteins that catalyze chemical reactions in the body and are involved in all
aspects of body functions, from producing energy, to digesting nutrients to
building macromolecules. Micronutrients play many essential roles in the body.
Table 1.1 Macro Minerals and Their Major Functions Minerals Major Functions
Sodium Fluid balance, nerve transmission, and muscle contraction Chloride Fluid
balance, stomach acid production Potassium Fluid balance, nerve transmission,
and muscle contraction Calcium Bone and teeth health maintenance, nerve
transmission, muscle contraction, and blood clotting Phosphorus Bone and teeth
health maintenance, acid-base balance Magnesium Protein production, nerve
transmission, and muscle contraction Sulfur Protein production Table 1.2 Trace
Minerals and Their Major Functions Minerals Major Functions Iron Carries oxygen,
assists in energy production Zinc Protein and DNA production, wound healing,
growth, and immune system function Iodine Thyroid hormone production, growth,
metabolism Selenium Antioxidant Copper Coenzyme, iron metabolism Manganese
Coenzyme Fluoride Bone and teeth health maintenance, tooth decay prevention
Chromium Assists in glucose metabolism Molybdenum Coenzyme 8 | INTRODUCTION
Page Number:8


Score:0.6572
Text:
Fact or Fiction Because they are needed in greater amounts, macronutrients are
more important than micronutrients in the diet. Figure 1.2 The Macronutrients:
Carbohydrates, Lipids, Protein, and Water (Source: University of Hawaii @ Manoa
[New Tab], CC-BY-NC-SA) Water There is one other nutrient that we must have in
large quantities: water. Water does not contain carbon but comprises two
hydrogen atoms and one oxygen atom per water molecule. More than 60 percent of
your total body weight is water. Without it, nothing could be transported in or
out of the body, chemical reactions would not occur, organs would not be
cushioned, and body temperature would fluctuate widely. An adult consumes just
over two liters of water daily from food and drink combined. Since water is so
critical for life’s basic processes, the amount of water input and output is
significant, a topic we will explore in detail in Chapter 4. Micronutrients
Micronutrients are nutrients required by the body in lesser amounts, but are
still essential for carrying out bodily functions. Micronutrients include all
the essential minerals and vitamins. There are sixteen essential minerals and
thirteen vitamins (See Table 1.1 “Macro Minerals and Their Major Functions”,
Table 1.2 “Micro Minerals and Their Major Functions”, Table 1.3 “Water-soluble
Vitamins and Their Major Functions”, and Table 1.4 “Fat-soluble Vitamins and
Their Major Functions” for a complete list and their major functions).
Page Number:7

Now lets use the reranking process.Means feri scores predict garxa ani highest scores lai first and desending.Predict garda query + chunks duitai ko score predict hunxa.

In [38]:
from sentence_transformers import CrossEncoder

#Load rerank model
reranker = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-6-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

In [39]:
query = "How to reduce the Risk of Cardiovascular Disease?"
# Extract top chunks (full dictionaries) using integer indices from filtered_chunks
top_chunks_dicts = [filtered_chunks[i.item()] for i in top_result_similarity[1]]

# Now pair query with the 'sentence_chunk' text from the extracted dictionaries
pairs = [[query, chunk_dict["sentence_chunk"]] for chunk_dict in top_chunks_dicts]

#print(pairs)

# Rerank scores
rerank_scores = reranker.predict(pairs)

# Now sort reranked scores along with the original chunk dictionaries
sorted_rerank_scores = sorted(zip(rerank_scores, top_chunks_dicts),
                                  key=lambda x: x[0],
                                  reverse=True)

for score, chunk_dict in sorted_rerank_scores:
  print(f"Score:{score:.4f}")
  print("Text:")
  print_wrapped(chunk_dict["sentence_chunk"])
  print(f"Page Number:{chunk_dict["page_number"]}")
  print("\n")

Score:-10.4124
Text:
Learning Objectives By the end of this chapter you will be able to: • Describe
the physiological changes that occur in response to exercise • Describe the
effects of physical fitness on overall health • Describe the purpose and
applications of nutrition supplements Becoming and staying physically fit is an
important part of achieving optimal health. A well-rounded exercise program is
crucial to becoming and remaining healthy. Physical activity improves your
health in a number of ways. It promotes weight loss, strengthens muscles and
bones, keeps the heart and lungs strong, and helps to protect against chronic
disease. There are four essential elements of physical fitness: cardio-
respiratory, muscular strength, flexibility, and maintaining a healthful body
composition. Some enthusiasts might argue the relative importance of each, but
optimal health requires some degree of balance between all four. For example
Louisiana offers a variety of endurance events throughout the year, as well as
triathlons that consist of 800m swim, 18-mile bike, 5K. 1 Some forms of exercise
confer multiple benefits, which can help you to balance the different elements
of physical fitness. For example, riding a bicycle for thirty minutes or more
not only builds cardio-respiratory endurance, it also improves muscle strength
and muscle endurance. Some forms of yoga can also build muscle strength and
endurance, along with flexibility. However, addressing fitness standards in all
four categories generally requires incorporating a range of activities into your
regular routine.
Page Number:688


Score:-11.2465
Text:
https://iopscience.iop.org/article/10.1088/1757-899X/190/1/012018. Accessed
August 7, 2025 692 | THE ESSENTIAL ELEMENTS OF PHYSICAL FITNESS
Page Number:692


Score:-11.3098
Text:
here: https://louis.pressbooks.pub/nutrition/?p=472#h5p-149 An interactive H5P
element has been excluded from this version of the text. You can view it online
here: https://louis.pressbooks.pub/nutrition/?p=472#h5p-150 696 | THE ESSENTIAL
ELEMENTS OF PHYSICAL FITNESS
Page Number:696

Lets make all this in function like return top k value and indices in func.

In [103]:
def retrieve_relavent_resources(query: str,embeddings: torch.tensor,model:SentenceTransformer= model):
  query_embeddings = model.encode(query,convert_to_tensor=True)

  #Get cosine similarity
  similarity = F.cosine_similarity(embeddings,query_embedings)

  #Get the top k results
  scores,indices = torch.topk(similarity,k=5)

  return scores,indices

In [104]:
def top_results_and_scores(query: str,embeddings: torch.tensor,filtered_chunks: list[dict]=filtered_chunks):
  scores,indices = retrieve_relavent_resources(query=query,embeddings=embeddings)
  for score,idx in zip(scores,indices):
    print(f"Score:{score:.4f}")
    print("Text:")
    print_wrapped(filtered_chunks[idx]["sentence_chunk"])
    print(f"Page Number:{filtered_chunks[idx]["page_number"]}")
    print("\n")

In [105]:
for item in filtered_chunks:
  if item["page_number"]==22:
    print(item["sentence_chunk"])

advisory that urged a warning be included on alcoholic beverages to state the potential risk of cancer associated with alcoholic beverage consumption.6 Illicit and prescription drug abuse are associated with decreased health and are a prominent problem in the United States. The health effects of drug abuse can be far-reaching, including the increased risk of stroke, heart disease, cancer, lung disease, and liver disease.7 Sleeping Patterns Inadequate amounts of sleep, or not sleeping well, can also have remarkable effects on a person’s health. In fact, sleeping can affect your health just as much as your diet. Scientific studies have shown that insufficient sleep increases the risk for heart disease, Type 2 diabetes, obesity, and depression. Abnormal breathing during sleep, a condition called sleep apnea, is also linked to an increased risk for chronic disease.8 Personal Choice: The Challenge of Choosing Foods Other factors besides environment and lifestyle influence the foods you choose to eat. Different foods affect energy level, mood, how much is eaten, how long before you eat again, and if cravings are satisfied. We have talked about some of the physical effects of food on your body, but there are other effects too.
Food regulates your appetite and how you feel. Multiple studies have demonstrated that some high fiber foods and high-protein foods decrease appetite by slowing the digestive process and prolonging the feeling of being full or satiety. The effects of individual foods and nutrients on mood are not backed by consistent scientific evidence, but in general, most studies support that healthier diets are associated with a decrease in depression and improved well-being. To date, science has not been able to track the exact path in the brain that occurs in response to eating a particular food, but it is quite clear that foods, in general, stimulate emotional responses in people. Food also has psychological, cultural, and religious significance, so your personal choices of food affect your mind, as well as your body. The social implications of food have a great deal to do with what people eat, as well as how and when. Special events in individual lives—from birthdays to funerals—are 6. U. S. Surgeon General Issues New Advisory on Link Between Alcohol and Cancer Risk. U. S. Department of Health and Human Services.https://www.hhs.gov/about/news/2025/01/03/us-surgeon-general-issues-new-advisory-link-alcohol-cancer-risk.html.
Accessed August 12, 2025.7. Research Topics. National Institute on Drug Abuse.https://www.drugabuse.gov/related-topics/health-consequences-drug-misuse. Accessed August 12, 2025.8. Sleep Disorders. National Sleep Foundation.https://sleepfoundation.org/sleep-disorders-problems.

In [106]:
query = "What are macronutrients and what are their roles?"
#retrieve_relavent_resources(query=query,embeddings=embeddings)
top_results_and_scores(query=query,embeddings=embeddings,filtered_chunks=filtered_chunks)

Score:0.7079
Text:
Macronutrients Nutrients that are needed in large amounts are called
macronutrients. There are three classes of macronutrients: carbohydrates,
lipids, and proteins. Through various biological processes occurring in the
body, these nutrients can be metabolized to produce cellular energy. The energy
from macronutrients comes from their chemical bonds. This chemical energy is
converted into cellular energy that is then utilized to perform work, allowing
our bodies to conduct their basic functions. The energy obtained from food,
which thus becomes cellular energy, is measured in calorie units. A unit of
measurement of food energy is the calorie. On nutrition food labels, the amount
given for “calories” is actually equivalent to each calorie multiplied by one
thousand. A kilocalorie (one thousand calories, denoted with a small “c”) is
synonymous with the “Calorie” (with a capital “C”) on nutrition food labels.
Although water does not yield calories, it is considered to be a macronutrient
because it is needed in large amounts daily.
Page Number:5


Score:0.6692
Text:
micronutrients are not sources of energy (calories), but they assist in the
process as cofactors or components of enzymes (i.e., coenzymes). Enzymes are
proteins that catalyze chemical reactions in the body and are involved in all
aspects of body functions, from producing energy, to digesting nutrients to
building macromolecules. Micronutrients play many essential roles in the body.
Table 1.1 Macro Minerals and Their Major Functions Minerals Major Functions
Sodium Fluid balance, nerve transmission, and muscle contraction Chloride Fluid
balance, stomach acid production Potassium Fluid balance, nerve transmission,
and muscle contraction Calcium Bone and teeth health maintenance, nerve
transmission, muscle contraction, and blood clotting Phosphorus Bone and teeth
health maintenance, acid-base balance Magnesium Protein production, nerve
transmission, and muscle contraction Sulfur Protein production Table 1.2 Trace
Minerals and Their Major Functions Minerals Major Functions Iron Carries oxygen,
assists in energy production Zinc Protein and DNA production, wound healing,
growth, and immune system function Iodine Thyroid hormone production, growth,
metabolism Selenium Antioxidant Copper Coenzyme, iron metabolism Manganese
Coenzyme Fluoride Bone and teeth health maintenance, tooth decay prevention
Chromium Assists in glucose metabolism Molybdenum Coenzyme 8 | INTRODUCTION
Page Number:8


Score:0.6572
Text:
Fact or Fiction Because they are needed in greater amounts, macronutrients are
more important than micronutrients in the diet. Figure 1.2 The Macronutrients:
Carbohydrates, Lipids, Protein, and Water (Source: University of Hawaii @ Manoa
[New Tab], CC-BY-NC-SA) Water There is one other nutrient that we must have in
large quantities: water. Water does not contain carbon but comprises two
hydrogen atoms and one oxygen atom per water molecule. More than 60 percent of
your total body weight is water. Without it, nothing could be transported in or
out of the body, chemical reactions would not occur, organs would not be
cushioned, and body temperature would fluctuate widely. An adult consumes just
over two liters of water daily from food and drink combined. Since water is so
critical for life’s basic processes, the amount of water input and output is
significant, a topic we will explore in detail in Chapter 4. Micronutrients
Micronutrients are nutrients required by the body in lesser amounts, but are
still essential for carrying out bodily functions. Micronutrients include all
the essential minerals and vitamins. There are sixteen essential minerals and
thirteen vitamins (See Table 1.1 “Macro Minerals and Their Major Functions”,
Table 1.2 “Micro Minerals and Their Major Functions”, Table 1.3 “Water-soluble
Vitamins and Their Major Functions”, and Table 1.4 “Fat-soluble Vitamins and
Their Major Functions” for a complete list and their major functions).
Page Number:7


Score:0.6458
Text:
Learning Objectives By the end of this chapter, you will be able to: • Define
nutrition. •Describe basic concepts in nutrition. •Describe factors that affect
your nutritional needs. •Describe the importance of research and scientific
methods to understanding nutrition. •Discuss nutrition as a science. What are
Nutrients?The foods we eat contain nutrients. Nutrients are substances required
by the body to perform its basic functions. Nutrients must be obtained from our
diet, since the human body does not synthesize or produce them. Nutrients have
one or more of three basic functions: they provide energy, contribute to body
structure, and/or regulate chemical processes in the body.
Page Number:4


Score:0.6432
Text:
These basic functions allow us to detect and respond to our environmental
surroundings, move, excrete wastes, respire (breathe), grow, and reproduce. Six
nutrients are required for the body to function and maintain overall health
(Figure 1.1). These are carbohydrates, lipids, proteins, water, vitamins, and
minerals. Foods also contain non-nutrients that may be harmful (such as natural
toxins common in plant foods and additives like some dyes and preservatives) or
beneficial (such as antioxidants). Figure 1.1 The six major nutrient classes
Macronutrients Micronutrients 4 | INTRODUCTION
Page Number:4

Getting an LLM for local generation

We're got our retrieval pipeline ready, let's now get the generation side of things happening.

To perform generation, we're going to use a Large Language Model (LLM).

LLMs are designed to generate an output given an input.

In our case, we want our LLM to generate and output of text given a input of text.

And more specifically, we want the output of text to be generated based on the context of relevant information to the query.

The input to an LLM is often referred to as a prompt.

We'll augment our prompt with a query as well as context from our textbook related to that query.

> **Which LLM should I use?**

There are many LLMs available.

Two of the main questions to ask from this is:
1. Do I want it to run locally?
2. If yes, how much compute power can I dedicate?

If you're after the absolute best performance, you'll likely want to use an API (not running locally) such as GPT-4 or Claude 3. However, this comes with the tradeoff of sending your data away and then awaiting a response.

For our case, since we want to set up a local pipeline and run it on our own GPU, we'd answer "yes" to the first question and then the second question will depend on what hardware we have available.

To find open-source LLMs, one great resource is the [Hugging Face open LLM leaderboard](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard).

The leaderboard compares many of the latest and greatest LLMs on various benchmarks.

Another great resource is [TheBloke on Hugging Face](https://huggingface.co/TheBloke), an account which provides an extensive range of quantized (models that have been made smaller) LLMs.

A rule of thumb for LLMs (and deep learning models in general) is that the higher the number of parameters, the better the model performs.

It may be tempting to go for the largest size model (e.g. a 70B parameter model rather than a 7B parameter model) but a larger size model may not be able to run on your available hardware.

The following table gives an insight into how much GPU memory you'll need to load an LLM with different sizes and different levels of [numerical precision](https://en.wikipedia.org/wiki/Precision_(computer_science)).

They are based on the fact that 1 float32 value (e.g. `0.69420`) requires 4 bytes of memory and 1GB is approximately 1,000,000,000 (one billion) bytes.

| Model Size (Billion Parameters) | Float32 VRAM (GB) | Float16 VRAM (GB) | 8-bit VRAM (GB) | 4-bit VRAM (GB) |
|-----|-----|-----|-----|-----|
| 1B                              | ~4                | ~2                | ~1              | ~0.5            |
| 7B (e.g., [Llama 2 7B](https://huggingface.co/meta-llama/Llama-2-7b), [Gemma 7B](https://huggingface.co/google/gemma-7b-it), [Mistral 7B](https://huggingface.co/mistralai/Mistral-7B-v0.1))             | ~28               | ~14               | ~7              | ~3.5            |
| 10B                             | ~40               | ~20               | ~10             | ~5              |
| 70B (e.g, Llama 2 70B)          | ~280              | ~140              | ~70             | ~35             |
| 100B                            | ~400              | ~200              | ~100            | ~50             |
| 175B                            | ~700              | ~350              | ~175            | ~87.5           |

<br>

> **Note:** Loading a model in a lower precision (e.g. 8-bit instead of float16) generally lowers performance. Lower precision can help to reduce computing requirements, however sometimes the performance degradation in terms of model output can be substantial. Finding the right speed/performance tradeoff will often require many experiments.

### Checking local GPU memory availability

Let's find out what hardware we've got available and see what kind of model(s) we'll be able to load.

> **Note:** You can also check this with the `!nvidia-smi` command.

In [44]:
# Get GPU available memory
import torch
gpu_memory_bytes = torch.cuda.get_device_properties(0).total_memory
gpu_memory_gb = round(gpu_memory_bytes / (2**30))
print(f"Available GPU memory: {gpu_memory_gb} GB")

Available GPU memory: 15 GB

Ok wonderful!

I'm running this notebook with a NVIDIA RTX 4090, so I've got 15GB of VRAM available.

However, this may be different on your end.

Looking at the table above, it seems we can run a ~7-10B parameter model in float4 precision pretty comfortably.

But we could also run a smaller one if we'd like.

Let's try out the recently released (at the time of writing, March 2024) LLM from Google, [Gemma](https://huggingface.co/blog/gemma).

Specifically, we'll use the `gemma-7b-it` version which stands for Gemma 7B Instruction-Tuned.

Instruction tuning is the process of tuning a raw language model to follow instructions.

These are the kind of models you'll find in most chat-based assistants such as ChatGPT, Gemini or Claude.

The following table shows different amounts of GPU memory requirements for different verions of the Gemma LLMs with varying levels of precision.

| Model             | Precision | Min-Memory (Bytes) | Min-Memory (MB) | Min-Memory (GB) | Recommended Memory (GB) | Hugging Face ID |
|-------------------|-----------|----------------|-------------|-------------| ----- | ----- |
| [Gemma 2B](https://huggingface.co/google/gemma-2b-it)          | 4-bit     | 2,106,749,952  | 2009.15     | 1.96        | ~5.0 | [`gemma-2b`](https://huggingface.co/google/gemma-2b) or [`gemma-2b-it`](https://huggingface.co/google/gemma-2b-it) for instruction tuned version |
| Gemma 2B          | Float16   | 5,079,453,696  | 4844.14     | 4.73        | ~8.0 | Same as above |
| [Gemma 7B](https://huggingface.co/google/gemma-7b-it)          | 4-bit     | 5,515,859,968  | 5260.33     | 5.14        | ~8.0 | [`gemma-7b`](https://huggingface.co/google/gemma-7b) or [`gemma-7b-it`](https://huggingface.co/google/gemma-7b-it) for instruction tuned version |
| Gemma 7B          | Float16   | 17,142,470,656 | 16348.33    | 15.97       | ~19 | Same as above |

> **Note:** `gemma-7b-it` means "instruction tuned", as in, a base LLM (`gemma-7b`) has been fine-tuned to follow instructions, similar to [`Mistral-7B-v0.1`](https://huggingface.co/mistralai/Mistral-7B-v0.1) and [`Mistral-7B-Instruct-v0.1`](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1).
>
> There are also further quantized and smaller variants of Gemma (and other LLMs) available in various formats such as GGUF. You can see many of these on [TheBloke account on Hugging Face](https://huggingface.co/TheBloke).
>
> The version of LLM you choose to use will be largely based on project requirements and experimentation.

Based on the table above, let's write a simple if/else statement which recommends which Gemma variant we should look into using.

In [45]:
# Note: the following is Gemma focused, however, there are more and more LLMs of the 2B and 7B size appearing for local use.
if gpu_memory_gb < 5.1:
    print(f"Your available GPU memory is {gpu_memory_gb}GB, you may not have enough memory to run a Gemma LLM locally without quantization.")
elif gpu_memory_gb < 8.1:
    print(f"GPU memory: {gpu_memory_gb} | Recommended model: Gemma 2B in 4-bit precision.")
    use_quantization_config = True
    model_id = "google/gemma-2b-it"
elif gpu_memory_gb < 19.0:
    print(f"GPU memory: {gpu_memory_gb} | Recommended model: Gemma 2B in float16 or Gemma 7B in 4-bit precision.")
    use_quantization_config = False
    model_id = "google/gemma-2b-it"
elif gpu_memory_gb > 19.0:
    print(f"GPU memory: {gpu_memory_gb} | Recommend model: Gemma 7B in 4-bit or float16 precision.")
    use_quantization_config = False
    model_id = "google/gemma-7b-it"

print(f"use_quantization_config set to: {use_quantization_config}")
print(f"model_id set to: {model_id}")

GPU memory: 15 | Recommended model: Gemma 2B in float16 or Gemma 7B in 4-bit precision.
use_quantization_config set to: False
model_id set to: google/gemma-2b-it

### Loading an LLM locally

Alright! Looks like `gemma-7b-it` it is (for my local machine with an RTX 4090, change the `model_id` and `use_quantization_config` values to suit your needs)!

There are plenty of examples of how to load the model on the `gemma-7b-it` [Hugging Face model card](https://huggingface.co/google/gemma-7b-it).

Good news is, the Hugging Face [`transformers`](https://huggingface.co/docs/transformers/) library has all the tools we need.

To load our LLM, we're going to need a few things:
1. A quantization config (optional) - This will determine whether or not we load the model in 4bit precision for lower memory usage. The we can create this with the [`transformers.BitsAndBytesConfig`](https://huggingface.co/docs/transformers/v4.38.2/en/main_classes/quantization#transformers.BitsAndBytesConfig) class (requires installing the [`bitsandbytes` library](https://github.com/TimDettmers/bitsandbytes)).
2. A model ID - This is the reference Hugging Face model ID which will determine which tokenizer and model gets used. For example `gemma-7b-it`.
3. A tokenzier - This is what will turn our raw text into tokens ready for the model. We can create it using the [`transformers.AutoTokenzier.from_pretrained`](https://huggingface.co/docs/transformers/v4.38.2/en/model_doc/auto#transformers.AutoTokenizer) method and passing it our model ID.
4. An LLM model - Again, using our model ID we can load a specific LLM model. To do so we can use the [`transformers.AutoModelForCausalLM.from_pretrained`](https://huggingface.co/docs/transformers/model_doc/auto#transformers.AutoModelForCausalLM.from_pretrained) method and passing it our model ID as well as other various parameters.

As a bonus, we'll check if [Flash Attention 2](https://huggingface.co/docs/transformers/perf_infer_gpu_one#flashattention-2) is available using `transformers.utils.is_flash_attn_2_available()`. Flash Attention 2 speeds up the attention mechanism in Transformer architecture models (which is what many modern LLMs are based on, including Gemma). So if it's available and the model is supported (not all models support Flash Attention 2), we'll use it. If it's not available, you can install it by following the instructions on the [GitHub repo](https://github.com/Dao-AILab/flash-attention).

> **Note:** Flash Attention 2 currently works on NVIDIA GPUs with a compute capability score of 8.0+ (Ampere, Ada Lovelace, Hopper architectures). We can check our GPU compute capability score with [`torch.cuda.get_device_capability(0)`](https://pytorch.org/docs/stable/generated/torch.cuda.get_device_capability.html).

> **Note:** To get access to the Gemma models, you will have to [agree to the terms & conditions](https://huggingface.co/google/gemma-7b-it) on the Gemma model page on Hugging Face. You will then have to authorize your local machine via the [Hugging Face CLI/Hugging Face Hub `login()` function](https://huggingface.co/docs/huggingface_hub/en/quick-start#authentication). Once you've done this, you'll be able to download the models. If you're using Google Colab, you can add a [Hugging Face token](https://huggingface.co/docs/hub/en/security-tokens) to the "Secrets" tab.
>
> Downloading an LLM locally can take a fair bit of time depending on your internet connection. Gemma 7B is about a 16GB download and Gemma 2B is about a 6GB download.

Let's do it!

In [107]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers.utils import is_flash_attn_2_available

# 1. Create quantization config for smaller model loading (optional)
# Requires !pip install bitsandbytes accelerate, see: https://github.com/TimDettmers/bitsandbytes, https://huggingface.co/docs/accelerate/
# For models that require 4-bit quantization (use this if you have low GPU memory available)
from transformers import BitsAndBytesConfig
quantization_config = BitsAndBytesConfig(load_in_4bit=True,
                                         bnb_4bit_compute_dtype=torch.float16)

# Bonus: Setup Flash Attention 2 for faster inference, default to "sdpa" or "scaled dot product attention" if it's not available
# Flash Attention 2 requires NVIDIA GPU compute capability of 8.0 or above, see: https://developer.nvidia.com/cuda-gpus
# Requires !pip install flash-attn, see: https://github.com/Dao-AILab/flash-attention
if (is_flash_attn_2_available()) and (torch.cuda.get_device_capability(0)[0] >= 8):
  attn_implementation = "flash_attention_2"
else:
  attn_implementation = "sdpa"
print(f"[INFO] Using attention implementation: {attn_implementation}")

# 2. Pick a model we'd like to use (this will depend on how much GPU memory you have available)
#model_id = "google/gemma-7b-it"
model_id = model_id # (we already set this above)
print(f"[INFO] Using model_id: {model_id}")

# 3. Instantiate tokenizer (tokenizer turns text into numbers ready for the model)
tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path=model_id)

# 4. Instantiate the model
llm_model = AutoModelForCausalLM.from_pretrained(pretrained_model_name_or_path=model_id,
                                                 torch_dtype=torch.float16, # datatype to use, we want float16
                                                 quantization_config=quantization_config if use_quantization_config else None,
                                                 low_cpu_mem_usage=False, # use full memory
                                                 attn_implementation=attn_implementation) # which attention version to use

if not use_quantization_config: # quantization takes care of device setting automatically, so if it's not used, send model to GPU
    llm_model.to("cuda")

[INFO] Using attention implementation: sdpa
[INFO] Using model_id: google/gemma-2b-it

Loading weights:   0%|          | 0/164 [00:00<?, ?it/s]

In [48]:
llm_model

GemmaForCausalLM(
  (model): GemmaModel(
    (embed_tokens): Embedding(256000, 2048, padding_idx=0)
    (layers): ModuleList(
      (0-17): 18 x GemmaDecoderLayer(
        (self_attn): GemmaAttention(
          (q_proj): Linear(in_features=2048, out_features=2048, bias=False)
          (k_proj): Linear(in_features=2048, out_features=256, bias=False)
          (v_proj): Linear(in_features=2048, out_features=256, bias=False)
          (o_proj): Linear(in_features=2048, out_features=2048, bias=False)
        )
        (mlp): GemmaMLP(
          (gate_proj): Linear(in_features=2048, out_features=16384, bias=False)
          (up_proj): Linear(in_features=2048, out_features=16384, bias=False)
          (down_proj): Linear(in_features=16384, out_features=2048, bias=False)
          (act_fn): GELUActivation()
        )
        (input_layernorm): GemmaRMSNorm((2048,), eps=1e-06)
        (post_attention_layernorm): GemmaRMSNorm((2048,), eps=1e-06)
      )
    )
    (norm): GemmaRMSNorm((2048,), eps=1e-06)
    (rotary_emb): GemmaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=2048, out_features=256000, bias=False)
)

In [49]:
#test
input_text = "Write a poem about machine learning."
input_ids = tokenizer(input_text,return_tensors="pt").to("cuda")
outputs = llm_model.generate(**input_ids)
print(tokenizer.decode(outputs[0]))

<bos>Write a poem about machine learning.

Machines, they weave and they learn,
From the data, they discern.
Algorithms,

In [50]:
#Nice way to do
input_text = "What are Macronutrients and their functions?"
print(f"Input text:\n{input_text}")

#create prompt template for instruction tuned model
dialogue_template = [
    {
        "role": "user",
        "content": input_text
    }
]

#Apply the chat template
prompt = tokenizer.apply_chat_template(conversation=dialogue_template,tokenize = False,add_generation_prompt=True)

print(f"Prompt Format:\n{prompt}")

Input text:
What are Macronutrients and their functions?
Prompt Format:
<bos><start_of_turn>user
What are Macronutrients and their functions?<end_of_turn>
<start_of_turn>model

In [51]:
#tokenize the input text
input_ids = tokenizer(prompt,return_tensors="pt").to("cuda")
input_ids

{'input_ids': tensor([[     2,      2,    106,   1645,    108,   1841,    708,  97586, 184592,
            578,   1024,   7257, 235336,    107,    108,    106,   2516,    108]],
       device='cuda:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
       device='cuda:0')}

In [52]:
#now generate the output
output = llm_model.generate(**input_ids,max_new_tokens = 250)
print(f"Output of model:{output[0]}")

Output of model:tensor([     2,      2,    106,   1645,    108,   1841,    708,  97586, 184592,
           578,   1024,   7257, 235336,    107,    108,    106,   2516,    108,
         21404, 235269,   1517, 235303, 235256,    476,  13367,    576,  97586,
        184592,    578,   1024,   7257, 235292,    109,    688,  12298,   1695,
        184592,    688,    708,  37132,    674,    573,   2971,   4026,    575,
          2910,  15992,    577,  10528,   1426,   2962, 235265,   2365,    708,
         13538,   1280,   1378,   1872,  14486, 235292, 186809, 184592,    578,
         92800, 184592, 235265,    109,    688,  12298,   1695, 184592,    688,
           708,  37132,    674,    573,   2971,   4026,    575,   8107,  15992,
        235265,   2365,    708,  13538,   1280,   2149,  14486, 235292,    109,
        235287,   5231, 156615,  56227,    688,   3658,   4134,    604,    573,
          2971, 235265,   2365,    708,   1942,    575,  16512,   1582,    685,
         11843, 235269,  22512, 235269,  12463, 235269,    578,  25741, 235265,
           108, 235287,   5231, 216954,    688,    708,   1671,    577,   2500,
           578,  12158,  29703, 235269,   7872,  44760, 235269,    578,   1501,
         53186, 235265,   2365,    708,   1942,    575,  16512,   1582,    685,
         11827, 235269,   5001, 235269,  12776, 235269,    578,  22604, 235265,
           108, 235287,   5231, 235311,   1989,    688,   3658,   4134, 235269,
          1707,  33398,  48765, 235269,    578,   2029,   7459,    573,   2971,
        235265,   2365,    708,   1942,    575,  16512,   1582,    685,   4684,
        235269,  10605, 235269,  22606, 235269,    578,  15741, 235265,    109,
           688,   5057,   1695, 184592,    688,    708,  37132,    674,    573,
          2971,   4026,    575,   9595,  15992, 235265,   2365,    708,  13538,
          1280,   1378,  14486, 235292,    109, 235287,   5231, 219033,    688,
           708,   4880,    604,   1767,  55786,   7257, 235269,   3359,  14354,
          2962, 235269,  24091,   1411, 235269,    578,  25606,  16102, 235265,
          2365,    708,   1942,    575,  16512,   1582,    685,   9512, 235269,
         13624, 235269,  22606, 235269,    578,  15741, 235265,    108, 235287,
          5231,  34212,  89092,    688,    708,   4880,    604,   1767,  55786,
          7257, 235269,   3359,  34883, 235269,   3027,   5115],
       device='cuda:0')

In [53]:
#now decode the token into text
output_decoded = tokenizer.decode(output[0])
print(f"Model Output:\n{output_decoded}\n")

Model Output:
<bos><bos><start_of_turn>user
What are Macronutrients and their functions?<end_of_turn>
<start_of_turn>model
Sure, here's a summary of Macronutrients and their functions:

**Macronutrients** are nutrients that the body needs in large amounts to maintain good health. They are divided into two main categories: macronutrients and micronutrients.

**Macronutrients** are nutrients that the body needs in larger amounts. They are divided into three categories:

* **Carbohydrates** provide energy for the body. They are found in foods such as bread, pasta, rice, and potatoes.
* **Proteins** are used to build and repair tissues, produce enzymes, and make hormones. They are found in foods such as meat, fish, eggs, and beans.
* **Fats** provide energy, help absorb vitamins, and insulate the body. They are found in foods such as oil, butter, nuts, and seeds.

**Micronutrients** are nutrients that the body needs in smaller amounts. They are divided into two categories:

* **Minerals** are needed for many bodily functions, including bone health, immune function, and nerve transmission. They are found in foods such as milk, cheese, nuts, and seeds.
* **Vitamins** are needed for many bodily functions, including metabolism, cell growth

Lets make a list of query we can try out for our pipelines.

In [108]:
# Nutrition-style questions generated with GPT4
gpt5_questions = [
    "What are the macronutrients, and what roles do they play in the human body?",
    "What is Osteoporosis, and what causes it?",
    "Describe the process of digestion and absorption of nutrients in the human body.",
    "How to reduce the Risk of Cardiovascular Disease?",
    "Explain the concept of energy balance and its importance in weight management.?"
]

# Manually created question list
manual_questions = [
     "What are the main classes of macronutrients?",
      "What are the steps to reducing the risk of cancer?",
      "What are the types of diabetes?",
      "What is Gestational Diabetes?",
      "How much water should an adult consume daily?"
]

In [109]:
query_list = gpt5_questions + manual_questions
query_list

['What are the macronutrients, and what roles do they play in the human body?',
 'What is Osteoporosis, and what causes it?',
 'Describe the process of digestion and absorption of nutrients in the human body.',
 'How to reduce the Risk of Cardiovascular Disease?',
 'Explain the concept of energy balance and its importance in weight management.?',
 'What are the main classes of macronutrients?',
 'What are the steps to reducing the risk of cancer?',
 'What are the types of diabetes?',
 'What is Gestational Diabetes?',
 'How much water should an adult consume daily?']

In [110]:
#lets generate relevant chunks in context of list of chunks we craeted earlier.
import random
query = random.choice(query_list)
scores,indices = retrieve_relavent_resources(query=query,embeddings=embeddings)
scores,indices

(tensor([0.7079, 0.6692, 0.6572, 0.6458, 0.6432], device='cuda:0'),
 tensor([21, 27, 26, 19, 20], device='cuda:0'))

# Agument Our query to the LLM for the best respose of our Query.

For augmentation we need to join the user query and retrival chunk then pass to LLM.

In [57]:
def prompt_formatter(query: str,retrieve_context: list[dict]):
  context = "- " + "\n-".join([item["sentence_chunk"] for item in retrieve_context])
#   base_prompt = f"""
# Based on the following context items, please answer the query.
# Give yourself room to think by extracting relevant passages from the context before answering the query.
# Don't return the thinking, only return the answer.
# Make sure your answers are as explanatory as possible.
# Use the following examples as reference for the ideal answer style.
# \nExample 1:
# Query: What are the fat-soluble vitamins?
# Answer: The fat-soluble vitamins include Vitamin A, Vitamin D, Vitamin E, and Vitamin K. These vitamins are absorbed along with fats in the diet and can be stored in the body's fatty tissue and liver for later use. Vitamin A is important for vision, immune function, and skin health. Vitamin D plays a critical role in calcium absorption and bone health. Vitamin E acts as an antioxidant, protecting cells from damage. Vitamin K is essential for blood clotting and bone metabolism.
# \nExample 2:
# Query: What are the causes of type 2 diabetes?
# Answer: Type 2 diabetes is often associated with overnutrition, particularly the overconsumption of calories leading to obesity. Factors include a diet high in refined sugars and saturated fats, which can lead to insulin resistance, a condition where the body's cells do not respond effectively to insulin. Over time, the pancreas cannot produce enough insulin to manage blood sugar levels, resulting in type 2 diabetes. Additionally, excessive caloric intake without sufficient physical activity exacerbates the risk by promoting weight gain and fat accumulation, particularly around the abdomen, further contributing to insulin resistance.
# \nExample 3:
# Query: What is the importance of hydration for physical performance?
# Answer: Hydration is crucial for physical performance because water plays key roles in maintaining blood volume, regulating body temperature, and ensuring the transport of nutrients and oxygen to cells. Adequate hydration is essential for optimal muscle function, endurance, and recovery. Dehydration can lead to decreased performance, fatigue, and increased risk of heat-related illnesses, such as heat stroke. Drinking sufficient water before, during, and after exercise helps ensure peak physical performance and recovery.
# \nNow use the following context items to answer the user query:
# {context}
# \nRelevant passages: <extract relevant passages from the context here>
# User query: {query}

# Answer: """

  base_prompt = f"""
  You are a helpful AI assistant.

  Use the following context to answer the question.
  If the answer is not in the context, say "I don't know".

  Context:
  {context}

  Question:
  {query}

  Answer:

  """

  print(f"Query:\n{query}")
  dialogue_template = [
      {
      "role": "user",
      "content":base_prompt
      }
      ]

  prompt = tokenizer.apply_chat_template(conversation=dialogue_template,tokenize=False,add_generation_prompt=True)
  return prompt

In [111]:
query = random.choice(query_list)

# Get relevant resources
scores, indices = retrieve_relavent_resources(query=query,
                                              embeddings=embeddings)

# Create a list of context items
retrieve_context = [filtered_chunks[i] for i in indices]

# Format prompt with context items
prompt = prompt_formatter(query=query,retrieve_context=retrieve_context)
print(prompt)

Query:
What is Osteoporosis, and what causes it?
<bos><start_of_turn>user
You are a helpful AI assistant.

  Use the following context to answer the question.
  If the answer is not in the context, say "I don't know".

  Context:
  - Macronutrients Nutrients that are needed in large amounts are called macronutrients. There are three classes of macronutrients: carbohydrates, lipids, and proteins. Through various biological processes occurring in the body, these nutrients can be metabolized to produce cellular energy. The energy from macronutrients comes from their chemical bonds. This chemical energy is converted into cellular energy that is then utilized to perform work, allowing our bodies to conduct their basic functions. The energy obtained from food, which thus becomes cellular energy, is measured in calorie units. A unit of measurement of food energy is the calorie. On nutrition food labels, the amount given for “calories” is actually equivalent to each calorie multiplied by one thousand. A kilocalorie (one thousand calories, denoted with a small “c”) is synonymous with the “Calorie” (with a capital “C”) on nutrition food labels. Although water does not yield calories, it is considered to be a macronutrient because it is needed in large amounts daily.
-micronutrients are not sources of energy (calories), but they assist in the process as cofactors or components of enzymes (i.e., coenzymes). Enzymes are proteins that catalyze chemical reactions in the body and are involved in all aspects of body functions, from producing energy, to digesting nutrients to building macromolecules. Micronutrients play many essential roles in the body. Table 1.1 Macro Minerals and Their Major Functions Minerals Major Functions Sodium Fluid balance, nerve transmission, and muscle contraction Chloride Fluid balance, stomach acid production Potassium Fluid balance, nerve transmission, and muscle contraction Calcium Bone and teeth health maintenance, nerve transmission, muscle contraction, and blood clotting Phosphorus Bone and teeth health maintenance, acid-base balance Magnesium Protein production, nerve transmission, and muscle contraction Sulfur Protein production Table 1.2 Trace Minerals and Their Major Functions Minerals Major Functions Iron Carries oxygen, assists in energy production Zinc Protein and DNA production, wound healing, growth, and immune system function Iodine Thyroid hormone production, growth, metabolism Selenium Antioxidant Copper Coenzyme, iron metabolism Manganese Coenzyme Fluoride Bone and teeth health maintenance, tooth decay prevention Chromium Assists in glucose metabolism Molybdenum Coenzyme 8 | INTRODUCTION
-Fact or Fiction Because they are needed in greater amounts, macronutrients are more important than micronutrients in the diet. Figure 1.2 The Macronutrients: Carbohydrates, Lipids, Protein, and Water (Source: University of Hawaii @ Manoa [New Tab], CC-BY-NC-SA) Water There is one other nutrient that we must have in large quantities: water. Water does not contain carbon but comprises two hydrogen atoms and one oxygen atom per water molecule. More than 60 percent of your total body weight is water. Without it, nothing could be transported in or out of the body, chemical reactions would not occur, organs would not be cushioned, and body temperature would fluctuate widely. An adult consumes just over two liters of water daily from food and drink combined. Since water is so critical for life’s basic processes, the amount of water input and output is significant, a topic we will explore in detail in Chapter 4. Micronutrients Micronutrients are nutrients required by the body in lesser amounts, but are still essential for carrying out bodily functions. Micronutrients include all the essential minerals and vitamins. There are sixteen essential minerals and thirteen vitamins (See Table 1.1 “Macro Minerals and Their Major Functions”, Table 1.2 “Micro Minerals and Their Major Functions”, Table 1.3 “Water-soluble Vitamins and Their Major Functions”, and Table 1.4 “Fat-soluble Vitamins and Their Major Functions” for a complete list and their major functions).
-Learning Objectives By the end of this chapter, you will be able to: • Define nutrition. •Describe basic concepts in nutrition. •Describe factors that affect your nutritional needs. •Describe the importance of research and scientific methods to understanding nutrition. •Discuss nutrition as a science. What are Nutrients?The foods we eat contain nutrients. Nutrients are substances required by the body to perform its basic functions. Nutrients must be obtained from our diet, since the human body does not synthesize or produce them. Nutrients have one or more of three basic functions: they provide energy, contribute to body structure, and/or regulate chemical processes in the body.
-These basic functions allow us to detect and respond to our environmental surroundings, move, excrete wastes, respire (breathe), grow, and reproduce. Six nutrients are required for the body to function and maintain overall health (Figure 1.1). These are carbohydrates, lipids, proteins, water, vitamins, and minerals. Foods also contain non-nutrients that may be harmful (such as natural toxins common in plant foods and additives like some dyes and preservatives) or beneficial (such as antioxidants). Figure 1.1 The six major nutrient classes Macronutrients Micronutrients 4 | INTRODUCTION

  Question:
  What is Osteoporosis, and what causes it?

  Answer:<end_of_turn>
<start_of_turn>model

Tokenize the prompt and pass to LLM.

In [112]:
input_ids = tokenizer(prompt,return_tensors="pt").to("cuda")
#output
output = llm_model.generate(**input_ids,temperature=0.1,do_sample=True,max_new_tokens=50)
decoded_output = tokenizer.decode(output[0])
print(f"Query: {query}")
print(f"RAG answer:\n{decoded_output.replace(prompt, '')}")

Query: What is Osteoporosis, and what causes it?
RAG answer:
<bos>The context does not provide information about Osteoporosis, so I cannot answer this question from the context.<eos>

Now Lets make function to do it.

In [113]:
def ask_query(query:str,
          temperature:int=0.7,
          max_new_token:int=250,
          format_answer_text=True,
          return_answer_only=True):

  ##RETRIEVAL
  #get the score and indices from relevant results
  scores,indices = retrieve_relavent_resources(query=query,embeddings=embeddings)

  #create a list of context retrieval
  retrieve_context = [filtered_chunks[i] for i in indices]

  #add score also in retrieve context
  for i,item in enumerate(retrieve_context):
    item["score"] = scores[i].cpu

  #AUGMENTATION
  prompt = prompt_formatter(query=query,retrieve_context=retrieve_context)


  #GENERATION
  input_ids = tokenizer(prompt,return_tensors="pt").to("cuda")

  output = llm_model.generate(**input_ids,temperature=temperature,do_sample=True,max_new_tokens=max_new_token)

  output = tokenizer.decode(output[0])

  #format the answer
  if format_answer_text:
    #replace prompt and special token
    output=output.replace(prompt,"").replace("<bos>","").replace("<eos>","")

  if return_answer_only:
    return output

In [114]:
query = random.choice(query_list)
print(f"Query:\n{query}")
ask_query(query=query)

Query:
What are the macronutrients, and what roles do they play in the human body?
Query:
What are the macronutrients, and what roles do they play in the human body?

"Sure, here is the answer to the question:\n\nThe macronutrients are carbohydrates, lipids, and proteins. They are all essential for the proper functioning of the human body. They provide energy for all the body's functions, including muscle contraction, nerve transmission, and cell growth."